-- ============================================================================
-- SCHEMA SNAPSHOT (somente documentacao) - capturado em 29/06/2026
-- Projeto Supabase: Igui_Banho_Tosa_Birigui (ref ihhylytyompvdhkphgud)
-- ============================================================================
--
-- IMPORTANTE: este arquivo NAO faz parte da sequencia de migrations real do
-- projeto (supabase/migrations/0001 ... 0029). Aquelas migrations continuam
-- sendo a fonte da verdade para reaplicar o schema do zero. Este arquivo e
-- uma FOTOGRAFIA do estado atual do banco, util para:
--   - consulta rapida de qualquer tabela sem precisar somar 25+ migrations;
--   - documentacao/onboarding;
--   - referencia para disaster recovery, se necessario recriar tudo de uma vez.
--
-- Gerado por introspeccao direta do banco (information_schema + pg_catalog),
-- nao por pg_dump (Docker indisponivel neste ambiente). Toda CREATE TABLE
-- usa IF NOT EXISTS para ser seguro de rodar sem quebrar nada.
--
-- Funcoes referenciadas nas constraints/RLS (is_master, can_access_unidade,
-- fiscal_can_*, cpf_valido, etc.) e triggers (set_updated_at,
-- validate_nota_fiscal_itens_total) NAO sao redefinidas aqui -- elas ja
-- existem no banco e suas definicoes completas estao espalhadas nas
-- migrations 0001-0029 (cada uma documentando a function que criou). Listar
-- aqui duplicaria ~15 functions sem necessidade para o objetivo deste
-- arquivo (documentar tabelas).
-- ============================================================================


-- ============================================================================
-- TIPOS ENUM CUSTOMIZADOS
-- ============================================================================
-- Observacao (inconsistencia encontrada): os enums abaixo existem no banco,
-- mas NENHUMA coluna de tabela os utiliza hoje -- todas as colunas de
-- "status" reais (agendamentos.status, pacotes.status, etc.) sao do tipo
-- `text` livre, com valores capitalizados diferentes dos enums (ex:
-- 'Agendado' no texto vs 'agendado' no enum agendamento_status). Os enums
-- parecem ter sido criados no planejamento inicial (0001_extensions_enums)
-- e depois abandonados em favor de texto livre. Mantidos aqui só por existirem
-- de fato no banco.

do $$ begin
  create type public.agendamento_status as enum ('agendado', 'confirmado', 'em_atendimento', 'finalizado', 'cancelado', 'faltou');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.pacote_status as enum ('ativo', 'concluido', 'cancelado', 'vencido');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.financeiro_tipo as enum ('receita', 'despesa', 'estorno');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.financeiro_status as enum ('pendente', 'parcial', 'pago', 'cancelado');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.forma_pagamento as enum ('pix', 'dinheiro', 'debito', 'credito', 'transferencia', 'outro');
exception when duplicate_object then null; end $$;

-- Usado de fato em funcionarios.cargo e usuarios_unidades.perfil.
-- Observacao: o frontend (types.ts UserRole) tambem usa 'comum' e
-- 'administrador' e o fallback 'pendente', mas nenhum desses 3 valores
-- existe neste enum -- eles nunca sao de fato gravados nessas colunas
-- (sao só estados puramente de frontend quando nao ha funcionario vinculado).
do $$ begin
  create type public.user_profile as enum ('master', 'admin_unidade', 'gerente', 'financeiro', 'atendente', 'tosador', 'somente_leitura');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.whatsapp_status as enum ('pendente', 'enviado', 'erro', 'ignorado');
exception when duplicate_object then null; end $$;


-- ============================================================================
-- 1. unidades
-- ============================================================================
-- Lojas/unidades da rede. Tabela raiz: quase todas as outras tabelas
-- referenciam unidade_id para isolamento multi-unidade via RLS.
create table if not exists public.unidades (
  id bigint generated by default as identity primary key,
  nome text not null,
  slug text not null,
  cnpj text,
  telefone text,
  endereco_completo text,
  ativo boolean not null default true,
  whatsapp_nome_instancia text,
  whatsapp_token text,
  whatsapp_url_servidor text,
  whatsapp_ativo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ============================================================================
-- 2. usuarios_perfis
-- ============================================================================
-- Catalogo descritivo dos perfis de acesso (enum user_profile). Tabela
-- pequena, so para exibir nome/descricao de cada perfil na UI.
create table if not exists public.usuarios_perfis (
  perfil public.user_profile primary key,
  nome text not null,
  descricao text,
  created_at timestamptz not null default now()
);


-- ============================================================================
-- 3. servicos
-- ============================================================================
-- Catalogo global de servicos (banho, tosa, etc.), independente de unidade.
create table if not exists public.servicos (
  id bigint generated by default as identity primary key,
  nome text not null,
  descricao text,
  preco_base numeric(10,2) not null default 0,
  duracao_minutos integer,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ============================================================================
-- 4. config_sistema
-- ============================================================================
-- Configuracao global da rede (nome fantasia, logo). Singleton (id=1).
create table if not exists public.config_sistema (
  id bigint generated by default as identity primary key,
  nome_fantasia text not null default 'iG Banho e Tosa',
  logo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ============================================================================
-- 5. clientes
-- ============================================================================
-- Tutores/clientes. unidade_id obrigatorio (isolamento RLS);
-- unidade_preferencial_id mantido por compatibilidade com o frontend antigo.
create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  unidade_preferencial_id bigint references public.unidades(id) on delete set null,
  nome text not null,
  telefone text,
  telefone_adicional text,
  email citext,
  cpf text,
  data_nascimento date,
  nacionalidade text default 'Brasil',
  genero text,
  receber_msgs boolean not null default true,
  notas_internas text,
  restricoes text,
  logradouro text,
  cep text,
  numero text,
  bairro text,
  complemento text,
  cidade text,
  estado text,
  foto_url text,
  origem_id text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ============================================================================
-- 6. funcionarios
-- ============================================================================
-- Usuarios operacionais vinculados ao Supabase Auth (auth.users via user_id).
create table if not exists public.funcionarios (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  unidade_id bigint references public.unidades(id) on delete set null,
  nome text not null,
  email citext,
  telefone text,
  cargo public.user_profile not null default 'atendente',
  ativo boolean not null default false,
  foto_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint funcionarios_email_key unique (email),
  constraint funcionarios_user_id_key unique (user_id)
);


-- ============================================================================
-- 7. usuarios_unidades
-- ============================================================================
-- Fonte de verdade para acesso por unidade/perfil (usada por is_master() e
-- can_access_unidade()). Um usuario auth pode ter varios vinculos, mas so
-- um ativo por vez (uq_usuarios_unidades_one_active_user).
create table if not exists public.usuarios_unidades (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  unidade_id bigint references public.unidades(id) on delete cascade,
  perfil public.user_profile not null default 'atendente',
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint usuarios_unidades_unidade_required_for_non_master
    check (perfil = 'master' or unidade_id is not null),
  constraint usuarios_unidades_unique_scope unique (user_id, unidade_id, perfil)
);


-- ============================================================================
-- 8. pets
-- ============================================================================
-- Pets/dependentes, vinculados a um cliente. unidade_id duplicado aqui (alem
-- de via clientes) para permitir RLS e indices diretos sem join.
create table if not exists public.pets (
  id bigint generated by default as identity primary key,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  nome text not null,
  data_nascimento date,
  genero text,
  especie text,
  raca text,
  porte text,
  comportamento text,
  notas_internas text,
  restricoes text,
  foto_url text,
  origem_id text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ============================================================================
-- 9. servicos_unidade
-- ============================================================================
-- Disponibilidade e preco (override opcional) de cada servico por unidade.
create table if not exists public.servicos_unidade (
  id bigint generated by default as identity primary key,
  unidade_id bigint not null references public.unidades(id) on delete cascade,
  servico_id bigint not null references public.servicos(id) on delete cascade,
  preco numeric(10,2),
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint servicos_unidade_unidade_id_servico_id_key unique (unidade_id, servico_id)
);


-- ============================================================================
-- 10. servicos_fiscais
-- ============================================================================
-- Configuracao fiscal (codigos municipais/nacionais, aliquota ISS) de cada
-- servico por unidade. Parte do modulo fiscal (migration 0019).
create table if not exists public.servicos_fiscais (
  id bigint generated by default as identity primary key,
  servico_id bigint not null references public.servicos(id) on delete cascade,
  unidade_id bigint not null references public.unidades(id) on delete cascade,
  ativo boolean not null default true,
  descricao_fiscal text,
  codigo_servico_municipal text,
  codigo_tributacao_nacional text,
  codigo_nbs text,
  aliquota_iss numeric(5,2),
  incidencia_iss text,
  observacoes_fiscais text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint servicos_fiscais_aliquota_non_negative
    check (aliquota_iss is null or aliquota_iss >= 0),
  constraint servicos_fiscais_unidade_id_servico_id_key unique (unidade_id, servico_id)
);


-- ============================================================================
-- 11. config_fiscal_unidade
-- ============================================================================
-- Configuracao fiscal geral de cada unidade (regime tributario, CNPJ,
-- ambiente NFS-e, etc.). Uma linha por unidade.
create table if not exists public.config_fiscal_unidade (
  id bigint generated by default as identity primary key,
  unidade_id bigint not null references public.unidades(id) on delete cascade,
  ativo boolean not null default false,
  ambiente_fiscal text not null default 'NAO_CONFIGURADO',
  regime_tributario text,
  razao_social text,
  nome_fantasia text,
  cnpj text,
  inscricao_municipal text,
  codigo_municipio_ibge text,
  municipio text,
  uf text,
  cep text,
  logradouro text,
  numero text,
  bairro text,
  complemento text,
  email_fiscal text,
  telefone_fiscal text,
  emitir_nota_automaticamente boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint config_fiscal_unidade_unidade_id_key unique (unidade_id)
);


-- ============================================================================
-- 12. configuracoes_sistema
-- ============================================================================
-- Configuracoes chave/valor (jsonb) genericas, globais ou por unidade.
-- Observacao (inconsistencia/duplicacao): coexiste com config_sistema, que
-- guarda nome_fantasia/logo_url num formato fixo (nao chave/valor). Os dois
-- nomes sao muito parecidos e podem confundir -- nenhum dos dois e referido
-- como "legado" no codigo, mas nao vi configuracoes_sistema sendo consumida
-- nos componentes que explorei nesta sessao.
create table if not exists public.configuracoes_sistema (
  id bigint generated by default as identity primary key,
  unidade_id bigint references public.unidades(id) on delete cascade,
  chave text not null,
  valor jsonb not null default '{}'::jsonb,
  descricao text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint configuracoes_sistema_unidade_id_chave_key unique (unidade_id, chave)
);


-- ============================================================================
-- 13. whatsapp_configuracoes
-- ============================================================================
-- Configuracao do provedor de WhatsApp (Evolution API) por unidade.
-- Observacao (duplicacao): os mesmos dados (whatsapp_nome_instancia,
-- whatsapp_token, whatsapp_url_servidor, whatsapp_ativo) tambem existem
-- como colunas diretas em unidades. As Edge Functions (lembrete-24h) leem
-- de unidades, nao desta tabela -- esta parece ter sido criada num
-- replanejamento (tabela dedicada) que nao chegou a ser adotado pelo codigo.
create table if not exists public.whatsapp_configuracoes (
  id bigint generated by default as identity primary key,
  unidade_id bigint not null references public.unidades(id) on delete cascade,
  provider text not null default 'evolution_api',
  nome_instancia text,
  url_servidor text,
  token_secret_name text,
  ativo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint whatsapp_configuracoes_unidade_id_key unique (unidade_id)
);


-- ============================================================================
-- 14. catalogo_pacotes
-- ============================================================================
-- Modelos de pacote reutilizaveis (ex: "Semanal R$160"), gerenciados em
-- Configuracoes > Pacotes. Catalogo global, independente de unidade.
create table if not exists public.catalogo_pacotes (
  id bigint generated by default as identity primary key,
  nome text not null,
  frequencia text not null check (frequencia in ('Weekly','Bi-weekly')),
  qtd_sessoes integer not null default 4 check (qtd_sessoes > 0),
  valor_base numeric(10,2) not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ============================================================================
-- 15. catalogo_pacotes_unidade
-- ============================================================================
-- Habilita/desabilita cada modelo de catalogo_pacotes por unidade.
create table if not exists public.catalogo_pacotes_unidade (
  id bigint generated by default as identity primary key,
  unidade_id bigint not null references public.unidades(id) on delete cascade,
  catalogo_pacote_id bigint not null references public.catalogo_pacotes(id) on delete cascade,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  constraint catalogo_pacotes_unidade_unidade_id_catalogo_pacote_id_key unique (unidade_id, catalogo_pacote_id)
);


-- ============================================================================
-- 16. pacotes
-- ============================================================================
-- Pacotes de fidelidade/recorrencia contratados por um cliente/pet.
-- catalogo_pacote_id (opcional) rastreia de qual modelo o pacote veio.
create table if not exists public.pacotes (
  id bigint generated by default as identity primary key,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  cliente_id bigint not null references public.clientes(id) on delete restrict,
  pet_id bigint not null references public.pets(id) on delete restrict,
  servico_id bigint references public.servicos(id) on delete set null,
  nome text,
  nome_pacote text,
  qtd_sessoes integer not null default 4 check (qtd_sessoes > 0),
  valor_total numeric(10,2) not null default 0,
  valor_transporte numeric(10,2) not null default 0,
  status text not null default 'Agendado',
  pago boolean not null default false,
  ativo boolean not null default true,
  forma_pagamento text,
  forma_pagamento_2 text,
  valor_pagamento_2 numeric(10,2) not null default 0,
  data_pagamento date,
  renovacao_automatica boolean not null default false,
  pacote_anterior_id bigint references public.pacotes(id) on delete set null,
  ciclo_renovacao integer not null default 1,
  data_inicio date,
  data_fim date,
  origem_id text,
  valor_desconto numeric(10,2) not null default 0,
  catalogo_pacote_id bigint references public.catalogo_pacotes(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ============================================================================
-- 17. agendamentos
-- ============================================================================
-- Agenda/sessoes. Quando pacote_id nao e nulo, a linha e uma sessao daquele
-- pacote (numero_sessao indica qual). valor_total e o valor cobrado NAQUELE
-- dia (proporcional, no caso de pacote) -- nao confundir com pacotes.valor_total.
create table if not exists public.agendamentos (
  id bigint generated by default as identity primary key,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  cliente_id bigint not null references public.clientes(id) on delete restrict,
  pet_id bigint not null references public.pets(id) on delete restrict,
  pacote_id bigint references public.pacotes(id) on delete set null,
  numero_sessao integer check (numero_sessao is null or numero_sessao > 0),
  funcionario_id bigint references public.funcionarios(id) on delete set null,
  data_agendamento date not null,
  horario_inicio time not null,
  horario_fim time,
  status text not null default 'Agendado',
  tem_taxi boolean not null default false,
  endereco_busca text,
  valor_servicos numeric(10,2) not null default 0,
  valor_transporte numeric(10,2) not null default 0,
  valor_total numeric(10,2) not null default 0,
  valor_desconto numeric(10,2) not null default 0 check (valor_desconto >= 0),
  pago boolean not null default false,
  forma_pagamento text,
  forma_pagamento_2 text,
  valor_pagamento_2 numeric(10,2) not null default 0,
  valor_extra_total numeric(10,2) not null default 0,
  status_pagamento_extra text not null default 'PENDENTE',
  forma_pagamento_extra text,
  data_pagamento_extra date,
  data_inicio_real timestamptz,
  data_fim_real timestamptz,
  lembrete_enviado boolean not null default false,
  notificar_ao_finalizar boolean not null default false,
  origem_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ============================================================================
-- 18. agendamento_itens
-- ============================================================================
-- Servicos (principais ou extras, ver eh_extra/tipo) dentro de um agendamento.
create table if not exists public.agendamento_itens (
  id bigint generated by default as identity primary key,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  agendamento_id bigint not null references public.agendamentos(id) on delete cascade,
  servico_id bigint references public.servicos(id) on delete set null,
  descricao text,
  tipo text not null default 'principal',
  eh_extra boolean not null default false,
  valor numeric(10,2),
  valor_extra numeric(10,2) not null default 0,
  valor_cobrado numeric(10,2) not null default 0,
  created_at timestamptz not null default now()
);


-- ============================================================================
-- 19. despesas
-- ============================================================================
-- Gastos/saidas financeiras de uma unidade.
create table if not exists public.despesas (
  id bigint generated by default as identity primary key,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  nome_item text not null,
  descricao text,
  quantidade integer not null default 1 check (quantidade > 0),
  valor_total numeric(10,2) not null default 0,
  data_despesa date not null default current_date,
  comprovante_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ============================================================================
-- 20. financeiro_movimentos
-- ============================================================================
-- Entradas/saidas/estornos financeiros (a obrigacao/receita/despesa em si).
create table if not exists public.financeiro_movimentos (
  id bigint generated by default as identity primary key,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  cliente_id bigint references public.clientes(id) on delete set null,
  pet_id bigint references public.pets(id) on delete set null,
  pacote_id bigint references public.pacotes(id) on delete set null,
  agendamento_id bigint references public.agendamentos(id) on delete set null,
  despesa_id bigint references public.despesas(id) on delete set null,
  tipo public.financeiro_tipo not null,
  categoria text not null,
  descricao text,
  valor_total numeric(10,2) not null default 0,
  data_competencia date not null default current_date,
  data_vencimento date,
  status public.financeiro_status not null default 'pendente',
  origem text,
  origem_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ============================================================================
-- 21. financeiro_pagamentos
-- ============================================================================
-- Pagamentos individuais (suporta pagamento dividido em N partes) de um
-- financeiro_movimentos.
create table if not exists public.financeiro_pagamentos (
  id bigint generated by default as identity primary key,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  movimento_id bigint not null references public.financeiro_movimentos(id) on delete cascade,
  forma_pagamento public.forma_pagamento not null,
  valor numeric(10,2) not null check (valor > 0),
  pago_em timestamptz not null default now(),
  observacao text,
  created_at timestamptz not null default now()
);


-- ============================================================================
-- 22. notas_fiscais
-- ============================================================================
-- Notas fiscais de servico (NFS-e), fase 1 (somente rascunho -- ver checks
-- notas_fiscais_status_fase1_check). Vinculada a exatamente um agendamento
-- OU um pacote (nunca os dois, ver notas_fiscais_origem_comercial_check).
create table if not exists public.notas_fiscais (
  id bigint generated by default as identity primary key,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  agendamento_id bigint references public.agendamentos(id) on delete restrict,
  pacote_id bigint references public.pacotes(id) on delete restrict,
  financeiro_movimento_id bigint not null references public.financeiro_movimentos(id) on delete restrict,
  financeiro_pagamento_id bigint references public.financeiro_pagamentos(id) on delete restrict,
  cliente_id bigint not null references public.clientes(id) on delete restrict,
  status text not null default 'RASCUNHO',
  ambiente text not null default 'NAO_CONFIGURADO',
  tipo_documento text not null default 'NFS_E',
  numero_nota text,
  codigo_verificacao text,
  chave_acesso text,
  url_documento text,
  url_pdf text,
  xml_documento text,
  data_confirmacao_pagamento timestamptz not null,
  data_competencia date,
  data_emissao timestamptz,
  data_cancelamento timestamptz,
  valor_servicos numeric(10,2) not null default 0,
  valor_desconto numeric(10,2) not null default 0,
  valor_total numeric(10,2) not null default 0,
  descricao_servico text,
  observacoes_fiscais text,
  tomador_nome text,
  tomador_cpf_cnpj text,
  tomador_email text,
  tomador_telefone text,
  tomador_endereco text,
  mensagem_rejeicao text,
  resposta_integracao jsonb,
  criada_por_user_id uuid default auth.uid() references auth.users(id) on delete set null,
  atualizada_por_user_id uuid references auth.users(id) on delete set null,
  emitida_por_user_id uuid references auth.users(id) on delete set null,
  cancelada_por_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint notas_fiscais_origem_comercial_check
    check ((agendamento_id is not null and pacote_id is null) or (agendamento_id is null and pacote_id is not null)),
  constraint notas_fiscais_status_check
    check (status = any (array['RASCUNHO','AGUARDANDO_CONFIGURACAO','PRONTA_PARA_EMITIR','EM_PROCESSAMENTO','EMITIDA','REJEITADA','CANCELADA'])),
  constraint notas_fiscais_status_fase1_check check (status = 'RASCUNHO'),
  constraint notas_fiscais_valores_non_negative
    check (valor_servicos >= 0 and valor_desconto >= 0 and valor_total >= 0
      and valor_desconto <= valor_servicos and valor_total = (valor_servicos - valor_desconto))
);


-- ============================================================================
-- 23. nota_fiscal_itens
-- ============================================================================
-- Itens (servicos) dentro de uma nota fiscal.
create table if not exists public.nota_fiscal_itens (
  id bigint generated by default as identity primary key,
  nota_fiscal_id bigint not null references public.notas_fiscais(id) on delete cascade,
  servico_id bigint references public.servicos(id) on delete set null,
  descricao text not null,
  observacoes_fiscais text,
  quantidade numeric(10,2) not null default 1,
  valor_unitario numeric(10,2) not null default 0,
  valor_desconto numeric(10,2) not null default 0,
  valor_total numeric(10,2) not null default 0,
  codigo_servico_municipal text,
  codigo_tributacao_nacional text,
  codigo_nbs text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint nota_fiscal_itens_valores_non_negative
    check (quantidade > 0 and valor_unitario >= 0 and valor_desconto >= 0 and valor_total >= 0
      and valor_desconto <= (quantidade * valor_unitario)
      and valor_total = ((quantidade * valor_unitario) - valor_desconto))
);
-- Triggers (definicao completa nao incluida neste snapshot, ver migration 0019):
--   validate_nota_fiscal_itens_total_insert/update/delete (deferrable, valida
--   que a soma dos itens bate com o valor_total da nota fiscal pai).


-- ============================================================================
-- 24. auditoria_logs
-- ============================================================================
-- Log estruturado de auditoria (acao, tabela, registro, dados_antes/depois).
create table if not exists public.auditoria_logs (
  id bigint generated by default as identity primary key,
  unidade_id bigint references public.unidades(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  usuario_email citext,
  usuario_nome text,
  acao text not null,
  tabela text,
  registro_id bigint,
  descricao text,
  dados_antes jsonb,
  dados_depois jsonb,
  ip inet,
  user_agent text,
  criado_em timestamptz not null default now(),
  created_at timestamptz not null default now()
);


-- ============================================================================
-- 25. logs_whatsapp
-- ============================================================================
-- Logs de envio de WhatsApp (formato mais antigo).
-- Observacao (inconsistencia): esta tabela NAO TEM NENHUMA FOREIGN KEY (nem
-- mesmo para unidades, apesar de ter a coluna unidade_id) -- diferente de
-- whatsapp_mensagens, que tem FKs completas para unidades/clientes/pets/
-- agendamentos. As duas tabelas tem colunas quase identicas; logs_whatsapp
-- parece ser a versao anterior, mantida por compatibilidade com codigo/dados
-- antigos, com whatsapp_mensagens sendo a versao atual e mais robusta.
create table if not exists public.logs_whatsapp (
  id bigint generated by default as identity primary key,
  unidade_id bigint not null,
  cliente_id bigint,
  pet_id bigint,
  agendamento_id bigint,
  telefone text,
  nome_cliente text,
  nome_pet text,
  tipo text not null default 'manual',
  tipo_agendamento text,
  mensagem text,
  status text not null default 'PENDENTE',
  provider_message_id text,
  detalhe_erro text,
  enviado_em timestamptz,
  criado_em timestamptz not null default now(),
  created_at timestamptz not null default now()
);


-- ============================================================================
-- 26. whatsapp_mensagens
-- ============================================================================
-- Logs de envio de WhatsApp (versao atual, com FKs completas). E nesta
-- tabela que a Edge Function lembrete-24h grava o resultado de cada envio.
create table if not exists public.whatsapp_mensagens (
  id bigint generated by default as identity primary key,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  cliente_id bigint references public.clientes(id) on delete set null,
  pet_id bigint references public.pets(id) on delete set null,
  agendamento_id bigint references public.agendamentos(id) on delete set null,
  telefone text,
  nome_cliente text,
  nome_pet text,
  tipo text not null default 'manual',
  tipo_agendamento text,
  mensagem text,
  status text not null default 'PENDENTE',
  provider_message_id text,
  detalhe_erro text,
  enviado_em timestamptz,
  criado_em timestamptz not null default now(),
  created_at timestamptz not null default now()
);


-- ============================================================================
-- 27. migration_imports
-- ============================================================================
-- Controle de execucoes de importacao de dados (planejado para a migracao
-- do sistema antigo -> V2). Existe desde a migration 0006, mas nao
-- encontrei nenhuma linha de codigo no frontend que grave nesta tabela --
-- parece nunca ter sido usada operacionalmente ainda.
create table if not exists public.migration_imports (
  id bigint generated by default as identity primary key,
  unidade_id bigint references public.unidades(id) on delete set null,
  origem text not null,
  tipo text not null,
  status text not null default 'planejado',
  total_registros integer not null default 0,
  total_importados integer not null default 0,
  total_erros integer not null default 0,
  iniciado_em timestamptz,
  finalizado_em timestamptz,
  created_at timestamptz not null default now()
);


-- ============================================================================
-- 28. migration_errors
-- ============================================================================
-- Erros por registro de uma execucao de migration_imports. Mesma observacao:
-- nao encontrei uso operacional no frontend ainda.
create table if not exists public.migration_errors (
  id bigint generated by default as identity primary key,
  import_id bigint not null references public.migration_imports(id) on delete cascade,
  tipo text not null,
  origem_id text,
  payload jsonb,
  erro text not null,
  created_at timestamptz not null default now()
);


-- ============================================================================
-- INDICES (alem dos criados automaticamente por PRIMARY KEY/UNIQUE acima)
-- ============================================================================

create index if not exists idx_agendamento_itens_agendamento_id on public.agendamento_itens using btree (agendamento_id);
create index if not exists idx_agendamento_itens_extra on public.agendamento_itens using btree (agendamento_id, eh_extra);
create index if not exists idx_agendamentos_unidade_data on public.agendamentos using btree (unidade_id, data_agendamento);
create index if not exists idx_auditoria_logs_unidade_created on public.auditoria_logs using btree (unidade_id, created_at desc);
create index if not exists idx_clientes_unidade_id on public.clientes using btree (unidade_id);
create index if not exists idx_config_fiscal_unidade_unidade on public.config_fiscal_unidade using btree (unidade_id);
create index if not exists idx_despesas_unidade_data on public.despesas using btree (unidade_id, data_despesa);
create index if not exists idx_financeiro_movimentos_unidade_data on public.financeiro_movimentos using btree (unidade_id, data_competencia);
create index if not exists idx_financeiro_pagamentos_movimento_id on public.financeiro_pagamentos using btree (movimento_id);
create index if not exists idx_funcionarios_unidade_id on public.funcionarios using btree (unidade_id);
create index if not exists idx_funcionarios_user_unidade on public.funcionarios using btree (user_id, unidade_id);
create index if not exists idx_logs_whatsapp_unidade_created on public.logs_whatsapp using btree (unidade_id, created_at desc);
create index if not exists idx_nota_fiscal_itens_nota on public.nota_fiscal_itens using btree (nota_fiscal_id);
create index if not exists idx_notas_fiscais_agendamento on public.notas_fiscais using btree (agendamento_id);
create index if not exists idx_notas_fiscais_cliente on public.notas_fiscais using btree (cliente_id);
create index if not exists idx_notas_fiscais_financeiro_movimento on public.notas_fiscais using btree (financeiro_movimento_id);
create index if not exists idx_notas_fiscais_financeiro_pagamento on public.notas_fiscais using btree (financeiro_pagamento_id);
create index if not exists idx_notas_fiscais_pacote on public.notas_fiscais using btree (pacote_id);
create index if not exists idx_notas_fiscais_unidade_competencia on public.notas_fiscais using btree (unidade_id, data_competencia desc);
create unique index if not exists uq_notas_fiscais_agendamento_movimento_ativo on public.notas_fiscais using btree (unidade_id, agendamento_id, financeiro_movimento_id) where (agendamento_id is not null and status <> 'CANCELADA');
create unique index if not exists uq_notas_fiscais_movimento_ativo on public.notas_fiscais using btree (financeiro_movimento_id) where (status <> 'CANCELADA');
create unique index if not exists uq_notas_fiscais_pacote_movimento_ativo on public.notas_fiscais using btree (unidade_id, pacote_id, financeiro_movimento_id) where (pacote_id is not null and status <> 'CANCELADA');
create index if not exists idx_pacotes_unidade_status on public.pacotes using btree (unidade_id, status);
create index if not exists idx_pets_cliente_id on public.pets using btree (cliente_id);
create index if not exists idx_pets_unidade_id on public.pets using btree (unidade_id);
create index if not exists idx_servicos_fiscais_servico on public.servicos_fiscais using btree (servico_id);
create index if not exists idx_servicos_fiscais_unidade on public.servicos_fiscais using btree (unidade_id);
create index if not exists idx_servicos_unidade_servico_id on public.servicos_unidade using btree (servico_id);
create index if not exists idx_servicos_unidade_unidade_id on public.servicos_unidade using btree (unidade_id);
create index if not exists idx_usuarios_unidades_unidade_id on public.usuarios_unidades using btree (unidade_id);
create index if not exists idx_usuarios_unidades_user_active on public.usuarios_unidades using btree (user_id, ativo);
create index if not exists idx_usuarios_unidades_user_id on public.usuarios_unidades using btree (user_id);
create unique index if not exists uq_usuarios_unidades_one_active_user on public.usuarios_unidades using btree (user_id) where (ativo = true);
create index if not exists idx_whatsapp_mensagens_unidade_created on public.whatsapp_mensagens using btree (unidade_id, created_at desc);


-- ============================================================================
-- FIM DO SNAPSHOT DE TABELAS
-- Continue em 20240002_rls_atual.sql para as politicas de RLS.
-- ============================================================================
