-- Sistema Pet V2 - reset schema to legacy-compatible bigint business IDs.
-- Destructive for test operational data. Auth users are not touched.

begin;

create temp table _old_config_sistema as
select * from public.config_sistema;

create temp table _old_unidades as
select * from public.unidades;

create temp table _old_funcionarios as
select * from public.funcionarios;

drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user() cascade;
drop function if exists public.is_master() cascade;
drop function if exists public.can_access_unidade(uuid) cascade;
drop function if exists public.can_access_unidade(bigint) cascade;

drop table if exists public.migration_errors cascade;
drop table if exists public.migration_imports cascade;
drop table if exists public.auditoria_logs cascade;
drop table if exists public.logs_whatsapp cascade;
drop table if exists public.whatsapp_mensagens cascade;
drop table if exists public.whatsapp_configuracoes cascade;
drop table if exists public.financeiro_pagamentos cascade;
drop table if exists public.financeiro_movimentos cascade;
drop table if exists public.despesas cascade;
drop table if exists public.agendamento_itens cascade;
drop table if exists public.agendamentos cascade;
drop table if exists public.pacotes cascade;
drop table if exists public.servicos_unidade cascade;
drop table if exists public.servicos cascade;
drop table if exists public.pets cascade;
drop table if exists public.clientes cascade;
drop table if exists public.funcionarios cascade;
drop table if exists public.usuarios_unidades cascade;
drop table if exists public.unidades cascade;
drop table if exists public.configuracoes_sistema cascade;
drop table if exists public.config_sistema cascade;

create table public.config_sistema (
  id bigint primary key generated by default as identity,
  nome_fantasia text not null default 'iG Banho e Tosa',
  logo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.unidades (
  id bigint primary key generated by default as identity,
  nome text not null,
  slug text not null unique,
  cnpj text,
  telefone text,
  endereco_completo text,
  ativo boolean not null default true,
  whatsapp_nome_instancia text,
  whatsapp_token text,
  whatsapp_url_servidor text,
  whatsapp_ativo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.configuracoes_sistema (
  id bigint primary key generated by default as identity,
  unidade_id bigint references public.unidades(id) on delete cascade,
  chave text not null,
  valor jsonb not null default '{}'::jsonb,
  descricao text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (unidade_id, chave)
);

create table public.usuarios_unidades (
  id bigint primary key generated by default as identity,
  user_id uuid not null references auth.users(id) on delete cascade,
  unidade_id bigint references public.unidades(id) on delete cascade,
  perfil public.user_profile not null default 'atendente',
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint usuarios_unidades_unidade_required_for_non_master check (perfil = 'master' or unidade_id is not null),
  constraint usuarios_unidades_unique_scope unique (user_id, unidade_id, perfil)
);

create table public.funcionarios (
  id bigint primary key generated by default as identity,
  user_id uuid unique references auth.users(id) on delete set null,
  unidade_id bigint references public.unidades(id) on delete set null,
  nome text not null,
  email citext unique,
  telefone text,
  cargo public.user_profile not null default 'atendente',
  ativo boolean not null default false,
  foto_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.clientes (
  id bigint primary key generated by default as identity,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  unidade_preferencial_id bigint references public.unidades(id) on delete set null,
  nome text not null,
  telefone text,
  telefone_adicional text,
  email citext,
  cpf text,
  data_nascimento date,
  nacionalidade text default 'Brasil',
  genero text,
  receber_msgs boolean not null default true,
  notas_internas text,
  restricoes text,
  logradouro text,
  cep text,
  numero text,
  bairro text,
  complemento text,
  cidade text,
  estado text,
  foto_url text,
  origem_id text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.pets (
  id bigint primary key generated by default as identity,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  nome text not null,
  data_nascimento date,
  genero text,
  especie text,
  raca text,
  porte text,
  comportamento text,
  notas_internas text,
  restricoes text,
  foto_url text,
  origem_id text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.servicos (
  id bigint primary key generated by default as identity,
  nome text not null unique,
  descricao text,
  preco_base numeric(10,2) not null default 0,
  duracao_minutos integer,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.servicos_unidade (
  id bigint primary key generated by default as identity,
  unidade_id bigint not null references public.unidades(id) on delete cascade,
  servico_id bigint not null references public.servicos(id) on delete cascade,
  preco numeric(10,2),
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (unidade_id, servico_id)
);

create table public.pacotes (
  id bigint primary key generated by default as identity,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  cliente_id bigint not null references public.clientes(id) on delete restrict,
  pet_id bigint not null references public.pets(id) on delete restrict,
  servico_id bigint references public.servicos(id) on delete set null,
  nome text,
  nome_pacote text,
  qtd_sessoes integer not null default 4 check (qtd_sessoes > 0),
  valor_total numeric(10,2) not null default 0,
  valor_transporte numeric(10,2) not null default 0,
  status text not null default 'Agendado',
  pago boolean not null default false,
  ativo boolean not null default true,
  forma_pagamento text,
  forma_pagamento_2 text,
  valor_pagamento_2 numeric(10,2) not null default 0,
  data_pagamento date,
  renovacao_automatica boolean not null default false,
  pacote_anterior_id bigint references public.pacotes(id) on delete set null,
  ciclo_renovacao integer not null default 1,
  data_inicio date,
  data_fim date,
  origem_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.agendamentos (
  id bigint primary key generated by default as identity,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  cliente_id bigint not null references public.clientes(id) on delete restrict,
  pet_id bigint not null references public.pets(id) on delete restrict,
  pacote_id bigint references public.pacotes(id) on delete set null,
  numero_sessao integer,
  funcionario_id bigint references public.funcionarios(id) on delete set null,
  data_agendamento date not null,
  horario_inicio time not null,
  horario_fim time,
  status text not null default 'Agendado',
  tem_taxi boolean not null default false,
  endereco_busca text,
  valor_servicos numeric(10,2) not null default 0,
  valor_transporte numeric(10,2) not null default 0,
  valor_total numeric(10,2) not null default 0,
  pago boolean not null default false,
  forma_pagamento text,
  forma_pagamento_2 text,
  valor_pagamento_2 numeric(10,2) not null default 0,
  valor_extra_total numeric(10,2) not null default 0,
  status_pagamento_extra text not null default 'PENDENTE',
  forma_pagamento_extra text,
  data_pagamento_extra date,
  data_inicio_real timestamptz,
  data_fim_real timestamptz,
  lembrete_enviado boolean not null default false,
  origem_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint agendamentos_numero_sessao_positive check (numero_sessao is null or numero_sessao > 0)
);

create table public.agendamento_itens (
  id bigint primary key generated by default as identity,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  agendamento_id bigint not null references public.agendamentos(id) on delete cascade,
  servico_id bigint references public.servicos(id) on delete set null,
  valor_cobrado numeric(10,2) not null default 0,
  created_at timestamptz not null default now()
);

create table public.despesas (
  id bigint primary key generated by default as identity,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  nome_item text not null,
  descricao text,
  quantidade integer not null default 1 check (quantidade > 0),
  valor_total numeric(10,2) not null default 0,
  data_despesa date not null default current_date,
  comprovante_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.financeiro_movimentos (
  id bigint primary key generated by default as identity,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  cliente_id bigint references public.clientes(id) on delete set null,
  pet_id bigint references public.pets(id) on delete set null,
  pacote_id bigint references public.pacotes(id) on delete set null,
  agendamento_id bigint references public.agendamentos(id) on delete set null,
  despesa_id bigint references public.despesas(id) on delete set null,
  tipo public.financeiro_tipo not null,
  categoria text not null,
  descricao text,
  valor_total numeric(10,2) not null default 0,
  data_competencia date not null default current_date,
  data_vencimento date,
  status public.financeiro_status not null default 'pendente',
  origem text,
  origem_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.financeiro_pagamentos (
  id bigint primary key generated by default as identity,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  movimento_id bigint not null references public.financeiro_movimentos(id) on delete cascade,
  forma_pagamento public.forma_pagamento not null,
  valor numeric(10,2) not null check (valor > 0),
  pago_em timestamptz not null default now(),
  observacao text,
  created_at timestamptz not null default now()
);

create table public.whatsapp_configuracoes (
  id bigint primary key generated by default as identity,
  unidade_id bigint not null unique references public.unidades(id) on delete cascade,
  provider text not null default 'evolution_api',
  nome_instancia text,
  url_servidor text,
  token_secret_name text,
  ativo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.whatsapp_mensagens (
  id bigint primary key generated by default as identity,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  cliente_id bigint references public.clientes(id) on delete set null,
  pet_id bigint references public.pets(id) on delete set null,
  agendamento_id bigint references public.agendamentos(id) on delete set null,
  telefone text,
  nome_cliente text,
  nome_pet text,
  tipo text not null default 'manual',
  tipo_agendamento text,
  mensagem text,
  status text not null default 'PENDENTE',
  provider_message_id text,
  detalhe_erro text,
  enviado_em timestamptz,
  criado_em timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table public.logs_whatsapp (like public.whatsapp_mensagens including all);

create table public.auditoria_logs (
  id bigint primary key generated by default as identity,
  unidade_id bigint references public.unidades(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  usuario_email citext,
  usuario_nome text,
  acao text not null,
  tabela text,
  registro_id bigint,
  descricao text,
  dados_antes jsonb,
  dados_depois jsonb,
  ip inet,
  user_agent text,
  criado_em timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table public.migration_imports (
  id bigint primary key generated by default as identity,
  unidade_id bigint references public.unidades(id) on delete set null,
  origem text not null,
  tipo text not null,
  status text not null default 'planejado',
  total_registros integer not null default 0,
  total_importados integer not null default 0,
  total_erros integer not null default 0,
  iniciado_em timestamptz,
  finalizado_em timestamptz,
  created_at timestamptz not null default now()
);

create table public.migration_errors (
  id bigint primary key generated by default as identity,
  import_id bigint not null references public.migration_imports(id) on delete cascade,
  tipo text not null,
  origem_id text,
  payload jsonb,
  erro text not null,
  created_at timestamptz not null default now()
);

create temp table _map_unidades (old_id uuid primary key, new_id bigint not null);

insert into public.config_sistema (id, nome_fantasia, logo_url, created_at, updated_at)
select id::bigint, nome_fantasia, logo_url, created_at, updated_at
from _old_config_sistema
on conflict (id) do update
set nome_fantasia = excluded.nome_fantasia,
    logo_url = excluded.logo_url,
    updated_at = excluded.updated_at;

insert into public.config_sistema (id, nome_fantasia, logo_url)
select 1, 'iG Banho e Tosa', null
where not exists (select 1 from public.config_sistema where id = 1);

select setval(
  pg_get_serial_sequence('public.config_sistema', 'id'),
  greatest((select coalesce(max(id), 1) from public.config_sistema), 1),
  true
);

with inserted as (
  insert into public.unidades (
    nome, slug, cnpj, telefone, endereco_completo, ativo,
    whatsapp_nome_instancia, whatsapp_token, whatsapp_url_servidor, whatsapp_ativo,
    created_at, updated_at
  )
  select
    nome,
    slug,
    cnpj,
    telefone,
    endereco_completo,
    ativo,
    whatsapp_nome_instancia,
    whatsapp_token,
    whatsapp_url_servidor,
    coalesce(whatsapp_ativo, false),
    created_at,
    updated_at
  from _old_unidades
  returning id, slug
)
insert into _map_unidades (old_id, new_id)
select ou.id, i.id
from _old_unidades ou
join inserted i on i.slug = ou.slug;

insert into public.unidades (id, nome, slug, telefone, endereco_completo, ativo)
select 1, 'Birigui', 'birigui', null, null, true
where not exists (select 1 from public.unidades);

select setval(
  pg_get_serial_sequence('public.unidades', 'id'),
  greatest((select coalesce(max(id), 1) from public.unidades), 1),
  true
);

insert into public.funcionarios (
  user_id, unidade_id, nome, email, telefone, cargo, ativo, foto_url, created_at, updated_at
)
select
  f.user_id,
  mu.new_id,
  f.nome,
  f.email,
  f.telefone,
  case
    when f.cargo::text in ('master','admin_unidade','gerente','financeiro','atendente','tosador','somente_leitura')
      then f.cargo
    else 'atendente'::public.user_profile
  end,
  f.ativo,
  f.foto_url,
  f.created_at,
  f.updated_at
from _old_funcionarios f
left join _map_unidades mu on mu.old_id = f.unidade_id;

insert into public.funcionarios (user_id, nome, email, cargo, ativo)
select u.id, coalesce(u.raw_user_meta_data->>'nome', split_part(u.email, '@', 1)), u.email, 'master', true
from auth.users u
where not exists (select 1 from public.funcionarios f where f.user_id = u.id)
order by u.created_at
limit 1;

insert into public.usuarios_unidades (user_id, unidade_id, perfil, ativo)
select user_id, null, 'master', true
from public.funcionarios
where cargo = 'master' and user_id is not null
on conflict do nothing;

insert into public.servicos (nome, descricao, preco_base, duracao_minutos, ativo)
values
  ('Banho Pequeno', 'Servico base de banho para porte pequeno', 55.00, 60, true),
  ('Banho Medio', 'Servico base de banho para porte medio', 70.00, 75, true),
  ('Tosa Higienica', 'Tosa higienica avulsa', 45.00, 45, true)
on conflict (nome) do nothing;

insert into public.servicos_unidade (unidade_id, servico_id, preco, ativo)
select u.id, s.id, s.preco_base, true
from public.unidades u
cross join public.servicos s
on conflict (unidade_id, servico_id) do nothing;

create trigger set_config_sistema_updated_at before update on public.config_sistema for each row execute function public.set_updated_at();
create trigger set_configuracoes_sistema_updated_at before update on public.configuracoes_sistema for each row execute function public.set_updated_at();
create trigger set_unidades_updated_at before update on public.unidades for each row execute function public.set_updated_at();
create trigger set_usuarios_unidades_updated_at before update on public.usuarios_unidades for each row execute function public.set_updated_at();
create trigger set_funcionarios_updated_at before update on public.funcionarios for each row execute function public.set_updated_at();
create trigger set_clientes_updated_at before update on public.clientes for each row execute function public.set_updated_at();
create trigger set_pets_updated_at before update on public.pets for each row execute function public.set_updated_at();
create trigger set_servicos_updated_at before update on public.servicos for each row execute function public.set_updated_at();
create trigger set_servicos_unidade_updated_at before update on public.servicos_unidade for each row execute function public.set_updated_at();
create trigger set_pacotes_updated_at before update on public.pacotes for each row execute function public.set_updated_at();
create trigger set_agendamentos_updated_at before update on public.agendamentos for each row execute function public.set_updated_at();
create trigger set_despesas_updated_at before update on public.despesas for each row execute function public.set_updated_at();
create trigger set_financeiro_movimentos_updated_at before update on public.financeiro_movimentos for each row execute function public.set_updated_at();
create trigger set_whatsapp_configuracoes_updated_at before update on public.whatsapp_configuracoes for each row execute function public.set_updated_at();

create index idx_usuarios_unidades_user_id on public.usuarios_unidades(user_id);
create index idx_usuarios_unidades_unidade_id on public.usuarios_unidades(unidade_id);
create index idx_funcionarios_unidade_id on public.funcionarios(unidade_id);
create index idx_clientes_unidade_id on public.clientes(unidade_id);
create index idx_pets_unidade_id on public.pets(unidade_id);
create index idx_pets_cliente_id on public.pets(cliente_id);
create index idx_servicos_unidade_unidade_id on public.servicos_unidade(unidade_id);
create index idx_servicos_unidade_servico_id on public.servicos_unidade(servico_id);
create index idx_pacotes_unidade_status on public.pacotes(unidade_id, status);
create index idx_agendamentos_unidade_data on public.agendamentos(unidade_id, data_agendamento);
create index idx_agendamento_itens_agendamento_id on public.agendamento_itens(agendamento_id);
create index idx_despesas_unidade_data on public.despesas(unidade_id, data_despesa);
create index idx_financeiro_movimentos_unidade_data on public.financeiro_movimentos(unidade_id, data_competencia);
create index idx_financeiro_pagamentos_movimento_id on public.financeiro_pagamentos(movimento_id);
create index idx_whatsapp_mensagens_unidade_created on public.whatsapp_mensagens(unidade_id, created_at desc);
create index idx_logs_whatsapp_unidade_created on public.logs_whatsapp(unidade_id, created_at desc);
create index idx_auditoria_logs_unidade_created on public.auditoria_logs(unidade_id, created_at desc);

create or replace function public.is_master()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.funcionarios f
    where f.user_id = auth.uid()
      and f.ativo = true
      and f.cargo = 'master'
  );
$$;

create or replace function public.can_access_unidade(target_unidade_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_master()
    or exists (
      select 1
      from public.usuarios_unidades uu
      where uu.user_id = auth.uid()
        and uu.ativo = true
        and uu.unidade_id = target_unidade_id
    )
    or exists (
      select 1
      from public.funcionarios f
      where f.user_id = auth.uid()
        and f.ativo = true
        and f.unidade_id = target_unidade_id
    );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  is_first_user boolean;
  display_name text;
  initial_profile public.user_profile := 'atendente';
  initial_active boolean := false;
begin
  select not exists (select 1 from public.funcionarios) into is_first_user;

  if is_first_user then
    initial_profile := 'master';
    initial_active := true;
  end if;

  display_name := coalesce(
    new.raw_user_meta_data->>'nome',
    new.raw_user_meta_data->>'full_name',
    initcap(split_part(new.email, '@', 1)),
    'Novo Funcionario'
  );

  insert into public.funcionarios (user_id, nome, email, cargo, ativo)
  values (new.id, display_name, new.email, initial_profile, initial_active)
  on conflict (user_id) do update
  set email = excluded.email,
      nome = coalesce(public.funcionarios.nome, excluded.nome);

  if is_first_user then
    insert into public.usuarios_unidades (user_id, unidade_id, perfil, ativo)
    values (new.id, null, 'master', true)
    on conflict do nothing;
  end if;

  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.config_sistema enable row level security;
alter table public.configuracoes_sistema enable row level security;
alter table public.unidades enable row level security;
alter table public.usuarios_unidades enable row level security;
alter table public.funcionarios enable row level security;
alter table public.clientes enable row level security;
alter table public.pets enable row level security;
alter table public.servicos enable row level security;
alter table public.servicos_unidade enable row level security;
alter table public.pacotes enable row level security;
alter table public.agendamentos enable row level security;
alter table public.agendamento_itens enable row level security;
alter table public.despesas enable row level security;
alter table public.financeiro_movimentos enable row level security;
alter table public.financeiro_pagamentos enable row level security;
alter table public.whatsapp_configuracoes enable row level security;
alter table public.whatsapp_mensagens enable row level security;
alter table public.logs_whatsapp enable row level security;
alter table public.auditoria_logs enable row level security;
alter table public.migration_imports enable row level security;
alter table public.migration_errors enable row level security;

create policy "config_sistema_read_authenticated" on public.config_sistema for select to authenticated using (true);
create policy "config_sistema_master_write" on public.config_sistema for all to authenticated using (public.is_master()) with check (public.is_master());
create policy "configuracoes_sistema_read_allowed" on public.configuracoes_sistema for select to authenticated using (public.is_master() or unidade_id is null or public.can_access_unidade(unidade_id));
create policy "configuracoes_sistema_master_write" on public.configuracoes_sistema for all to authenticated using (public.is_master()) with check (public.is_master());

create policy "unidades_select_master_or_unit" on public.unidades for select to authenticated using (public.is_master() or public.can_access_unidade(id));
create policy "unidades_insert_master" on public.unidades for insert to authenticated with check (public.is_master());
create policy "unidades_update_master" on public.unidades for update to authenticated using (public.is_master()) with check (public.is_master());
create policy "unidades_delete_master" on public.unidades for delete to authenticated using (public.is_master());

create policy "usuarios_unidades_read_allowed" on public.usuarios_unidades for select to authenticated using (public.is_master() or user_id = auth.uid() or public.can_access_unidade(unidade_id));
create policy "usuarios_unidades_master_write" on public.usuarios_unidades for all to authenticated using (public.is_master()) with check (public.is_master());
create policy "funcionarios_read_allowed" on public.funcionarios for select to authenticated using (public.is_master() or user_id = auth.uid() or public.can_access_unidade(unidade_id));
create policy "funcionarios_master_write" on public.funcionarios for all to authenticated using (public.is_master()) with check (public.is_master());

create policy "servicos_select_authenticated" on public.servicos for select to authenticated using (true);
create policy "servicos_insert_master" on public.servicos for insert to authenticated with check (public.is_master());
create policy "servicos_update_master" on public.servicos for update to authenticated using (public.is_master()) with check (public.is_master());
create policy "servicos_delete_master" on public.servicos for delete to authenticated using (public.is_master());

create policy "clientes_unit_access" on public.clientes for all to authenticated using (public.can_access_unidade(unidade_id)) with check (public.can_access_unidade(unidade_id));
create policy "pets_unit_access" on public.pets for all to authenticated using (public.can_access_unidade(unidade_id)) with check (public.can_access_unidade(unidade_id));
create policy "servicos_unidade_unit_access" on public.servicos_unidade for all to authenticated using (public.can_access_unidade(unidade_id)) with check (public.can_access_unidade(unidade_id));
create policy "pacotes_unit_access" on public.pacotes for all to authenticated using (public.can_access_unidade(unidade_id)) with check (public.can_access_unidade(unidade_id));
create policy "agendamentos_unit_access" on public.agendamentos for all to authenticated using (public.can_access_unidade(unidade_id)) with check (public.can_access_unidade(unidade_id));
create policy "agendamento_itens_unit_access" on public.agendamento_itens for all to authenticated using (public.can_access_unidade(unidade_id)) with check (public.can_access_unidade(unidade_id));
create policy "despesas_unit_access" on public.despesas for all to authenticated using (public.can_access_unidade(unidade_id)) with check (public.can_access_unidade(unidade_id));
create policy "financeiro_movimentos_unit_access" on public.financeiro_movimentos for all to authenticated using (public.can_access_unidade(unidade_id)) with check (public.can_access_unidade(unidade_id));
create policy "financeiro_pagamentos_unit_access" on public.financeiro_pagamentos for all to authenticated using (public.can_access_unidade(unidade_id)) with check (public.can_access_unidade(unidade_id));
create policy "whatsapp_configuracoes_unit_access" on public.whatsapp_configuracoes for all to authenticated using (public.can_access_unidade(unidade_id)) with check (public.can_access_unidade(unidade_id));
create policy "whatsapp_mensagens_unit_access" on public.whatsapp_mensagens for all to authenticated using (public.can_access_unidade(unidade_id)) with check (public.can_access_unidade(unidade_id));
create policy "logs_whatsapp_unit_access" on public.logs_whatsapp for all to authenticated using (public.can_access_unidade(unidade_id)) with check (public.can_access_unidade(unidade_id));
create policy "auditoria_logs_read_allowed" on public.auditoria_logs for select to authenticated using (public.is_master() or public.can_access_unidade(unidade_id));
create policy "auditoria_logs_insert_allowed" on public.auditoria_logs for insert to authenticated with check (public.is_master() or public.can_access_unidade(unidade_id));
create policy "migration_imports_master_only" on public.migration_imports for all to authenticated using (public.is_master()) with check (public.is_master());
create policy "migration_errors_master_only" on public.migration_errors for all to authenticated using (public.is_master()) with check (public.is_master());

commit;
