-- Sistema Pet V2 - Fiscal Fase 1.
-- Estrutura interna para rascunhos de NFS-e, sem emissao real e sem integracao externa.

begin;

create or replace function public.fiscal_profile_for_unidade(target_unidade_id bigint)
returns public.user_profile
language sql
stable
security definer
set search_path = public
as $$
  select case
    when public.is_master() then 'master'::public.user_profile
    else coalesce(
      (
        select uu.perfil
        from public.usuarios_unidades uu
        where uu.user_id = auth.uid()
          and uu.ativo = true
          and uu.unidade_id = target_unidade_id
        order by uu.id
        limit 1
      ),
      (
        select f.cargo
        from public.funcionarios f
        where f.user_id = auth.uid()
          and f.ativo = true
          and f.unidade_id = target_unidade_id
        order by f.id
        limit 1
      )
    )
  end;
$$;

create or replace function public.fiscal_can_view_config(target_unidade_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_master()
    or (
      public.can_access_unidade(target_unidade_id)
      and public.fiscal_profile_for_unidade(target_unidade_id) = 'financeiro'
    );
$$;

create or replace function public.fiscal_can_view_note(target_unidade_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_master()
    or (
      public.can_access_unidade(target_unidade_id)
      and public.fiscal_profile_for_unidade(target_unidade_id) in ('financeiro', 'admin_unidade', 'gerente')
    );
$$;

create or replace function public.fiscal_can_create_draft(target_unidade_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_master()
    or (
      public.can_access_unidade(target_unidade_id)
      and public.fiscal_profile_for_unidade(target_unidade_id) = 'financeiro'
    );
$$;

create or replace function public.fiscal_can_edit_draft(target_unidade_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.fiscal_can_view_note(target_unidade_id);
$$;

create or replace function public.fiscal_can_delete_draft(target_unidade_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_master()
    or (
      public.can_access_unidade(target_unidade_id)
      and public.fiscal_profile_for_unidade(target_unidade_id) = 'financeiro'
    );
$$;

create or replace function public.fiscal_can_manage_config(target_unidade_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_master() and public.can_access_unidade(target_unidade_id);
$$;

create table if not exists public.config_fiscal_unidade (
  id bigint primary key generated by default as identity,
  unidade_id bigint not null unique references public.unidades(id) on delete cascade,
  ativo boolean not null default false,
  ambiente_fiscal text not null default 'NAO_CONFIGURADO',
  regime_tributario text,
  razao_social text,
  nome_fantasia text,
  cnpj text,
  inscricao_municipal text,
  codigo_municipio_ibge text,
  municipio text,
  uf text,
  cep text,
  logradouro text,
  numero text,
  bairro text,
  complemento text,
  email_fiscal text,
  telefone_fiscal text,
  emitir_nota_automaticamente boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.servicos_fiscais (
  id bigint primary key generated by default as identity,
  servico_id bigint not null references public.servicos(id) on delete cascade,
  unidade_id bigint not null references public.unidades(id) on delete cascade,
  ativo boolean not null default true,
  descricao_fiscal text,
  codigo_servico_municipal text,
  codigo_tributacao_nacional text,
  codigo_nbs text,
  aliquota_iss numeric(5,2),
  incidencia_iss text,
  observacoes_fiscais text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (unidade_id, servico_id),
  constraint servicos_fiscais_aliquota_non_negative check (aliquota_iss is null or aliquota_iss >= 0)
);

create table if not exists public.notas_fiscais (
  id bigint primary key generated by default as identity,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  agendamento_id bigint references public.agendamentos(id) on delete restrict,
  pacote_id bigint references public.pacotes(id) on delete restrict,
  financeiro_movimento_id bigint not null references public.financeiro_movimentos(id) on delete restrict,
  financeiro_pagamento_id bigint references public.financeiro_pagamentos(id) on delete restrict,
  cliente_id bigint not null references public.clientes(id) on delete restrict,
  status text not null default 'RASCUNHO',
  ambiente text not null default 'NAO_CONFIGURADO',
  tipo_documento text not null default 'NFS_E',
  numero_nota text,
  codigo_verificacao text,
  chave_acesso text,
  url_documento text,
  url_pdf text,
  xml_documento text,
  data_confirmacao_pagamento timestamptz not null,
  data_competencia date,
  data_emissao timestamptz,
  data_cancelamento timestamptz,
  valor_servicos numeric(10,2) not null default 0,
  valor_desconto numeric(10,2) not null default 0,
  valor_total numeric(10,2) not null default 0,
  descricao_servico text,
  observacoes_fiscais text,
  tomador_nome text,
  tomador_cpf_cnpj text,
  tomador_email text,
  tomador_telefone text,
  tomador_endereco text,
  mensagem_rejeicao text,
  resposta_integracao jsonb,
  criada_por_user_id uuid default auth.uid() references auth.users(id) on delete set null,
  atualizada_por_user_id uuid references auth.users(id) on delete set null,
  emitida_por_user_id uuid references auth.users(id) on delete set null,
  cancelada_por_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint notas_fiscais_status_check check (status in (
    'RASCUNHO',
    'AGUARDANDO_CONFIGURACAO',
    'PRONTA_PARA_EMITIR',
    'EM_PROCESSAMENTO',
    'EMITIDA',
    'REJEITADA',
    'CANCELADA'
  )),
  constraint notas_fiscais_status_fase1_check check (status = 'RASCUNHO'),
  constraint notas_fiscais_origem_comercial_check check (
    (agendamento_id is not null and pacote_id is null)
    or (agendamento_id is null and pacote_id is not null)
  ),
  constraint notas_fiscais_valores_non_negative check (
    valor_servicos >= 0
    and valor_desconto >= 0
    and valor_total >= 0
    and valor_desconto <= valor_servicos
    and valor_total = valor_servicos - valor_desconto
  )
);

create table if not exists public.nota_fiscal_itens (
  id bigint primary key generated by default as identity,
  nota_fiscal_id bigint not null references public.notas_fiscais(id) on delete cascade,
  servico_id bigint references public.servicos(id) on delete set null,
  descricao text not null,
  observacoes_fiscais text,
  quantidade numeric(10,2) not null default 1,
  valor_unitario numeric(10,2) not null default 0,
  valor_desconto numeric(10,2) not null default 0,
  valor_total numeric(10,2) not null default 0,
  codigo_servico_municipal text,
  codigo_tributacao_nacional text,
  codigo_nbs text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint nota_fiscal_itens_valores_non_negative check (
    quantidade > 0
    and valor_unitario >= 0
    and valor_desconto >= 0
    and valor_total >= 0
    and valor_desconto <= (quantidade * valor_unitario)
    and valor_total = (quantidade * valor_unitario) - valor_desconto
  )
);

create or replace function public.fiscal_safe_audit(
  p_unidade_id bigint,
  p_acao text,
  p_tabela text,
  p_registro_id bigint,
  p_descricao text,
  p_dados_antes jsonb default null,
  p_dados_depois jsonb default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.auditoria_logs (
    unidade_id,
    user_id,
    acao,
    tabela,
    registro_id,
    descricao,
    dados_antes,
    dados_depois
  ) values (
    p_unidade_id,
    auth.uid(),
    p_acao,
    p_tabela,
    p_registro_id,
    p_descricao,
    p_dados_antes,
    p_dados_depois
  );
exception when others then
  null;
end;
$$;

create or replace function public.fiscal_validate_note_items_total(target_nota_fiscal_id bigint)
returns void
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  header_total numeric(10,2);
  items_total numeric(10,2);
begin
  select nf.valor_servicos into header_total
  from public.notas_fiscais nf
  where nf.id = target_nota_fiscal_id;

  if header_total is null then
    return;
  end if;

  select coalesce(sum(nfi.valor_total), 0)::numeric(10,2) into items_total
  from public.nota_fiscal_itens nfi
  where nfi.nota_fiscal_id = target_nota_fiscal_id;

  if items_total <> header_total then
    raise exception 'Total dos itens fiscais (%) difere do valor de servicos da nota fiscal (%)', items_total, header_total;
  end if;
end;
$$;

create or replace function public.fiscal_validate_note_items_total_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_id bigint;
begin
  target_id := coalesce(new.nota_fiscal_id, old.nota_fiscal_id);
  perform public.fiscal_validate_note_items_total(target_id);
  return coalesce(new, old);
end;
$$;

create or replace function public.fiscal_protect_nota_fiscal()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' then
    if old.status is distinct from 'RASCUNHO' then
      raise exception 'Somente rascunhos fiscais podem ser editados nesta fase.';
    end if;

    if (
      to_jsonb(new) - array[
        'data_competencia',
        'descricao_servico',
        'observacoes_fiscais',
        'tomador_nome',
        'tomador_cpf_cnpj',
        'tomador_email',
        'tomador_telefone',
        'tomador_endereco',
        'atualizada_por_user_id',
        'updated_at'
      ]::text[]
    ) <> (
      to_jsonb(old) - array[
        'data_competencia',
        'descricao_servico',
        'observacoes_fiscais',
        'tomador_nome',
        'tomador_cpf_cnpj',
        'tomador_email',
        'tomador_telefone',
        'tomador_endereco',
        'atualizada_por_user_id',
        'updated_at'
      ]::text[]
    ) then
      raise exception 'Somente data de competencia, descricao, observacoes fiscais e dados do tomador podem ser alterados no rascunho fiscal nesta fase.';
    end if;

    new.atualizada_por_user_id := auth.uid();

    perform public.fiscal_safe_audit(
      new.unidade_id,
      'EDICAO_RASCUNHO_FISCAL',
      'notas_fiscais',
      new.id,
      'Editou campos permitidos do rascunho fiscal #' || new.id::text || '.',
      jsonb_build_object(
        'data_competencia', old.data_competencia,
        'descricao_servico', old.descricao_servico,
        'observacoes_fiscais', old.observacoes_fiscais,
        'tomador_nome', old.tomador_nome,
        'tomador_email', old.tomador_email,
        'tomador_telefone', old.tomador_telefone,
        'tomador_endereco', old.tomador_endereco
      ),
      jsonb_build_object(
        'data_competencia', new.data_competencia,
        'descricao_servico', new.descricao_servico,
        'observacoes_fiscais', new.observacoes_fiscais,
        'tomador_nome', new.tomador_nome,
        'tomador_email', new.tomador_email,
        'tomador_telefone', new.tomador_telefone,
        'tomador_endereco', new.tomador_endereco
      )
    );
  end if;

  return new;
end;
$$;

create or replace function public.fiscal_protect_nota_fiscal_item()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  note_status text;
  note_unidade_id bigint;
begin
  select nf.status, nf.unidade_id
    into note_status, note_unidade_id
  from public.notas_fiscais nf
  where nf.id = coalesce(new.nota_fiscal_id, old.nota_fiscal_id);

  if note_status is distinct from 'RASCUNHO' then
    raise exception 'Itens fiscais so podem ser alterados enquanto a nota estiver em rascunho.';
  end if;

  if tg_op = 'UPDATE' then
    if old.nota_fiscal_id is distinct from new.nota_fiscal_id
      or old.servico_id is distinct from new.servico_id
      or old.quantidade is distinct from new.quantidade
      or old.valor_unitario is distinct from new.valor_unitario
      or old.valor_desconto is distinct from new.valor_desconto
      or old.valor_total is distinct from new.valor_total
      or old.codigo_servico_municipal is distinct from new.codigo_servico_municipal
      or old.codigo_tributacao_nacional is distinct from new.codigo_tributacao_nacional
      or old.codigo_nbs is distinct from new.codigo_nbs then
      raise exception 'Servico, valores e codigos fiscais dos itens nao podem ser alterados diretamente no rascunho fiscal.';
    end if;

    perform public.fiscal_safe_audit(
      note_unidade_id,
      'EDICAO_ITEM_RASCUNHO_FISCAL',
      'nota_fiscal_itens',
      new.id,
      'Editou descricao/observacoes permitidas do item fiscal #' || new.id::text || '.',
      jsonb_build_object('descricao', old.descricao, 'observacoes_fiscais', old.observacoes_fiscais),
      jsonb_build_object('descricao', new.descricao, 'observacoes_fiscais', new.observacoes_fiscais)
    );
  end if;

  return coalesce(new, old);
end;
$$;

create or replace function public.fiscal_audit_config_fiscal_unidade()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_row public.config_fiscal_unidade;
begin
  target_row := coalesce(new, old);

  perform public.fiscal_safe_audit(
    target_row.unidade_id,
    case
      when tg_op = 'INSERT' then 'CRIACAO_CONFIG_FISCAL'
      when tg_op = 'UPDATE' then 'EDICAO_CONFIG_FISCAL'
      else 'EXCLUSAO_CONFIG_FISCAL'
    end,
    'config_fiscal_unidade',
    target_row.id,
    case
      when tg_op = 'INSERT' then 'Criou configuracao fiscal da unidade.'
      when tg_op = 'UPDATE' then 'Editou configuracao fiscal da unidade.'
      else 'Excluiu configuracao fiscal da unidade.'
    end,
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) - 'cnpj' else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) - 'cnpj' else null end
  );

  return target_row;
end;
$$;

create or replace function public.fiscal_audit_servicos_fiscais()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_row public.servicos_fiscais;
begin
  target_row := coalesce(new, old);

  perform public.fiscal_safe_audit(
    target_row.unidade_id,
    case
      when tg_op = 'INSERT' then 'CRIACAO_SERVICO_FISCAL'
      when tg_op = 'UPDATE' then 'EDICAO_SERVICO_FISCAL'
      else 'EXCLUSAO_SERVICO_FISCAL'
    end,
    'servicos_fiscais',
    target_row.id,
    case
      when tg_op = 'INSERT' then 'Criou classificacao fiscal de servico.'
      when tg_op = 'UPDATE' then 'Editou classificacao fiscal de servico.'
      else 'Excluiu classificacao fiscal de servico.'
    end,
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end
  );

  return target_row;
end;
$$;

create or replace function public.fiscal_audit_nota_delete()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.fiscal_safe_audit(
    old.unidade_id,
    'EXCLUSAO_RASCUNHO_FISCAL',
    'notas_fiscais',
    old.id,
    'Excluiu rascunho fiscal #' || old.id::text || '.',
    jsonb_build_object(
      'id', old.id,
      'financeiro_movimento_id', old.financeiro_movimento_id,
      'agendamento_id', old.agendamento_id,
      'pacote_id', old.pacote_id,
      'valor_total', old.valor_total,
      'status', old.status
    ),
    null
  );

  return old;
end;
$$;

create or replace function public.criar_rascunho_fiscal_por_movimento(p_movimento_id bigint)
returns public.notas_fiscais
language plpgsql
security definer
set search_path = public
as $$
declare
  movimento public.financeiro_movimentos;
  cliente public.clientes;
  agendamento public.agendamentos;
  pacote public.pacotes;
  nota public.notas_fiscais;
  last_payment_id bigint;
  last_payment_at timestamptz;
  item_count integer;
  source_count integer;
  fiscal_subtotal numeric(10,2);
  non_fiscal_total numeric(10,2);
  expected_fiscal_total numeric(10,2);
  fiscal_discount numeric(10,2);
  tolerance numeric(10,2) := 0.01;
  fiscal_description text := 'Prestação de serviços de higiene, embelezamento e cuidados de animais domésticos.';
begin
  if auth.uid() is null then
    raise exception 'Usuario autenticado obrigatorio para criar rascunho fiscal.';
  end if;

  select *
    into movimento
  from public.financeiro_movimentos fm
  where fm.id = p_movimento_id
  for update;

  if not found then
    raise exception 'Movimento financeiro % nao encontrado.', p_movimento_id;
  end if;

  if not public.fiscal_can_create_draft(movimento.unidade_id) then
    raise exception 'Usuario sem permissao para criar rascunho fiscal nesta unidade.';
  end if;

  if movimento.tipo is distinct from 'receita'::public.financeiro_tipo then
    raise exception 'Somente movimentos de receita podem gerar rascunho fiscal.';
  end if;

  if movimento.status is distinct from 'pago'::public.financeiro_status then
    raise exception 'Rascunho fiscal so pode ser criado para movimento financeiro quitado.';
  end if;

  source_count :=
    case when movimento.agendamento_id is not null then 1 else 0 end
    + case when movimento.pacote_id is not null then 1 else 0 end;

  if source_count <> 1 then
    raise exception 'Movimento financeiro precisa ter exatamente uma origem comercial: agendamento ou pacote.';
  end if;

  if exists (
    select 1
    from public.notas_fiscais nf
    where nf.financeiro_movimento_id = movimento.id
      and nf.status <> 'CANCELADA'
  ) then
    perform public.fiscal_safe_audit(
      movimento.unidade_id,
      'TENTATIVA_DUPLICAR_RASCUNHO_FISCAL',
      'financeiro_movimentos',
      movimento.id,
      'Tentativa de criar rascunho fiscal duplicado para movimento financeiro #' || movimento.id::text || '.',
      null,
      jsonb_build_object('financeiro_movimento_id', movimento.id)
    );

    raise exception 'Ja existe rascunho fiscal ativo para este movimento financeiro.';
  end if;

  select fp.id, fp.pago_em
    into last_payment_id, last_payment_at
  from public.financeiro_pagamentos fp
  where fp.movimento_id = movimento.id
  order by fp.pago_em desc, fp.id desc
  limit 1;

  if last_payment_id is null or last_payment_at is null then
    raise exception 'Movimento financeiro quitado nao possui pagamento confirmado vinculado.';
  end if;

  if movimento.agendamento_id is not null then
    select *
      into agendamento
    from public.agendamentos a
    where a.id = movimento.agendamento_id;

    if not found then
      raise exception 'Agendamento de origem nao encontrado.';
    end if;

    select *
      into cliente
    from public.clientes c
    where c.id = coalesce(movimento.cliente_id, agendamento.cliente_id);

    if not found then
      raise exception 'Cliente de origem nao encontrado.';
    end if;

    select coalesce(sum(item_value), 0)::numeric(10,2)
      into fiscal_subtotal
    from (
      select coalesce(nullif(ai.valor, 0), nullif(ai.valor_cobrado, 0), nullif(ai.valor_extra, 0), 0)::numeric(10,2) as item_value
      from public.agendamento_itens ai
      join public.servicos s on s.id = ai.servico_id
      join public.servicos_fiscais sf
        on sf.unidade_id = movimento.unidade_id
       and sf.servico_id = ai.servico_id
       and sf.ativo = true
      where ai.agendamento_id = agendamento.id
        and coalesce(nullif(ai.valor, 0), nullif(ai.valor_cobrado, 0), nullif(ai.valor_extra, 0), 0) > 0
        and lower(s.nome) not like '%taxi%'
        and lower(s.nome) not like '%táxi%'
        and lower(s.nome) not like '%transporte%'
        and lower(s.nome) not like '%desloc%'
        and lower(s.nome) not like '%produto%'
    ) fiscal_items;

    non_fiscal_total := greatest(coalesce(agendamento.valor_transporte, 0), 0)::numeric(10,2);
    expected_fiscal_total := (movimento.valor_total - non_fiscal_total)::numeric(10,2);

    if fiscal_subtotal <= 0 then
      raise exception 'Nao foi possivel montar o rascunho fiscal automaticamente porque nenhum item fiscal elegivel de banho e tosa foi encontrado.';
    end if;

    if expected_fiscal_total <= 0 then
      raise exception 'Nao foi possivel montar o rascunho fiscal automaticamente porque o valor fiscal apos excluir receitas nao fiscais ficou zerado ou negativo.';
    end if;

    if fiscal_subtotal + tolerance < expected_fiscal_total then
      raise exception 'Nao foi possivel montar o rascunho fiscal automaticamente porque os itens de servico nao conferem com o valor financeiro recebido. Revise o atendimento financeiro antes de criar o rascunho.';
    end if;

    fiscal_discount := (fiscal_subtotal - expected_fiscal_total)::numeric(10,2);

    if fiscal_discount < 0 then
      fiscal_discount := 0;
    end if;

    insert into public.notas_fiscais (
      unidade_id,
      agendamento_id,
      pacote_id,
      financeiro_movimento_id,
      financeiro_pagamento_id,
      cliente_id,
      status,
      ambiente,
      tipo_documento,
      data_confirmacao_pagamento,
      data_competencia,
      data_emissao,
      valor_servicos,
      valor_desconto,
      valor_total,
      descricao_servico,
      tomador_nome,
      tomador_cpf_cnpj,
      tomador_email,
      tomador_telefone,
      tomador_endereco,
      criada_por_user_id
    ) values (
      movimento.unidade_id,
      agendamento.id,
      null,
      movimento.id,
      last_payment_id,
      cliente.id,
      'RASCUNHO',
      'NAO_CONFIGURADO',
      'NFS_E',
      last_payment_at,
      agendamento.data_agendamento,
      null,
      fiscal_subtotal,
      fiscal_discount,
      expected_fiscal_total,
      fiscal_description,
      cliente.nome,
      cliente.cpf,
      cliente.email::text,
      cliente.telefone,
      concat_ws(', ',
        nullif(concat_ws(' ', cliente.logradouro, cliente.numero), ''),
        nullif(cliente.bairro, ''),
        nullif(cliente.cidade, ''),
        nullif(cliente.estado, ''),
        nullif(cliente.cep, '')
      ),
      auth.uid()
    )
    returning * into nota;

    insert into public.nota_fiscal_itens (
      nota_fiscal_id,
      servico_id,
      descricao,
      quantidade,
      valor_unitario,
      valor_desconto,
      valor_total,
      codigo_servico_municipal,
      codigo_tributacao_nacional,
      codigo_nbs
    )
    select
      nota.id,
      ai.servico_id,
      coalesce(nullif(ai.descricao, ''), s.nome),
      1,
      coalesce(nullif(ai.valor, 0), nullif(ai.valor_cobrado, 0), nullif(ai.valor_extra, 0), 0)::numeric(10,2),
      0,
      coalesce(nullif(ai.valor, 0), nullif(ai.valor_cobrado, 0), nullif(ai.valor_extra, 0), 0)::numeric(10,2),
      sf.codigo_servico_municipal,
      sf.codigo_tributacao_nacional,
      sf.codigo_nbs
    from public.agendamento_itens ai
    join public.servicos s on s.id = ai.servico_id
    join public.servicos_fiscais sf
      on sf.unidade_id = movimento.unidade_id
     and sf.servico_id = ai.servico_id
     and sf.ativo = true
    where ai.agendamento_id = agendamento.id
      and coalesce(nullif(ai.valor, 0), nullif(ai.valor_cobrado, 0), nullif(ai.valor_extra, 0), 0) > 0
      and lower(s.nome) not like '%taxi%'
      and lower(s.nome) not like '%táxi%'
      and lower(s.nome) not like '%transporte%'
      and lower(s.nome) not like '%desloc%'
      and lower(s.nome) not like '%produto%';

    get diagnostics item_count = row_count;

    if item_count = 0 then
      raise exception 'Nao foi possivel montar o rascunho fiscal automaticamente porque nenhum item fiscal elegivel de banho e tosa foi encontrado.';
    end if;
  else
    select *
      into pacote
    from public.pacotes p
    where p.id = movimento.pacote_id;

    if not found then
      raise exception 'Pacote de origem nao encontrado.';
    end if;

    select *
      into cliente
    from public.clientes c
    where c.id = coalesce(movimento.cliente_id, pacote.cliente_id);

    if not found then
      raise exception 'Cliente de origem nao encontrado.';
    end if;

    non_fiscal_total := greatest(coalesce(pacote.valor_transporte, 0), 0)::numeric(10,2);
    expected_fiscal_total := (movimento.valor_total - non_fiscal_total)::numeric(10,2);

    if expected_fiscal_total <= 0 then
      raise exception 'Nao foi possivel montar o rascunho fiscal automaticamente porque o valor fiscal do pacote ficou zerado ou negativo.';
    end if;

    insert into public.notas_fiscais (
      unidade_id,
      agendamento_id,
      pacote_id,
      financeiro_movimento_id,
      financeiro_pagamento_id,
      cliente_id,
      status,
      ambiente,
      tipo_documento,
      data_confirmacao_pagamento,
      data_competencia,
      data_emissao,
      valor_servicos,
      valor_desconto,
      valor_total,
      descricao_servico,
      tomador_nome,
      tomador_cpf_cnpj,
      tomador_email,
      tomador_telefone,
      tomador_endereco,
      criada_por_user_id
    ) values (
      movimento.unidade_id,
      null,
      pacote.id,
      movimento.id,
      last_payment_id,
      cliente.id,
      'RASCUNHO',
      'NAO_CONFIGURADO',
      'NFS_E',
      last_payment_at,
      null,
      null,
      expected_fiscal_total,
      0,
      expected_fiscal_total,
      fiscal_description,
      cliente.nome,
      cliente.cpf,
      cliente.email::text,
      cliente.telefone,
      concat_ws(', ',
        nullif(concat_ws(' ', cliente.logradouro, cliente.numero), ''),
        nullif(cliente.bairro, ''),
        nullif(cliente.cidade, ''),
        nullif(cliente.estado, ''),
        nullif(cliente.cep, '')
      ),
      auth.uid()
    )
    returning * into nota;

    insert into public.nota_fiscal_itens (
      nota_fiscal_id,
      servico_id,
      descricao,
      quantidade,
      valor_unitario,
      valor_desconto,
      valor_total,
      codigo_servico_municipal,
      codigo_tributacao_nacional,
      codigo_nbs
    )
    select
      nota.id,
      pacote.servico_id,
      coalesce(s.nome, pacote.nome_pacote, pacote.nome, 'Pacote de banho e tosa'),
      1,
      expected_fiscal_total,
      0,
      expected_fiscal_total,
      sf.codigo_servico_municipal,
      sf.codigo_tributacao_nacional,
      sf.codigo_nbs
    from public.pacotes p
    left join public.servicos s on s.id = p.servico_id
    join public.servicos_fiscais sf
      on sf.unidade_id = movimento.unidade_id
     and sf.servico_id = p.servico_id
     and sf.ativo = true
     and nullif(btrim(sf.codigo_servico_municipal), '') is not null
     and nullif(btrim(sf.codigo_nbs), '') is not null
    where p.id = pacote.id;

    get diagnostics item_count = row_count;

    if item_count <> 1 then
      raise exception 'Nao foi possivel criar o rascunho fiscal porque o servico do pacote ainda nao possui configuracao fiscal ativa.';
    end if;
  end if;

  perform public.fiscal_validate_note_items_total(nota.id);

  perform public.fiscal_safe_audit(
    movimento.unidade_id,
    'CRIACAO_RASCUNHO_FISCAL',
    'notas_fiscais',
    nota.id,
    'Criou rascunho fiscal #' || nota.id::text || ' para movimento financeiro #' || movimento.id::text || '.',
    null,
    jsonb_build_object(
      'nota_fiscal_id', nota.id,
      'financeiro_movimento_id', movimento.id,
      'agendamento_id', nota.agendamento_id,
      'pacote_id', nota.pacote_id,
      'valor_total', nota.valor_total
    )
  );

  return nota;
end;
$$;

drop trigger if exists set_config_fiscal_unidade_updated_at on public.config_fiscal_unidade;
create trigger set_config_fiscal_unidade_updated_at
before update on public.config_fiscal_unidade
for each row execute function public.set_updated_at();

drop trigger if exists audit_config_fiscal_unidade_changes on public.config_fiscal_unidade;
create trigger audit_config_fiscal_unidade_changes
after insert or update or delete on public.config_fiscal_unidade
for each row execute function public.fiscal_audit_config_fiscal_unidade();

drop trigger if exists set_servicos_fiscais_updated_at on public.servicos_fiscais;
create trigger set_servicos_fiscais_updated_at
before update on public.servicos_fiscais
for each row execute function public.set_updated_at();

drop trigger if exists audit_servicos_fiscais_changes on public.servicos_fiscais;
create trigger audit_servicos_fiscais_changes
after insert or update or delete on public.servicos_fiscais
for each row execute function public.fiscal_audit_servicos_fiscais();

drop trigger if exists set_notas_fiscais_updated_at on public.notas_fiscais;
create trigger set_notas_fiscais_updated_at
before update on public.notas_fiscais
for each row execute function public.set_updated_at();

drop trigger if exists protect_notas_fiscais_integrity on public.notas_fiscais;
create trigger protect_notas_fiscais_integrity
before update on public.notas_fiscais
for each row execute function public.fiscal_protect_nota_fiscal();

drop trigger if exists audit_notas_fiscais_delete on public.notas_fiscais;
create trigger audit_notas_fiscais_delete
after delete on public.notas_fiscais
for each row execute function public.fiscal_audit_nota_delete();

drop trigger if exists set_nota_fiscal_itens_updated_at on public.nota_fiscal_itens;
create trigger set_nota_fiscal_itens_updated_at
before update on public.nota_fiscal_itens
for each row execute function public.set_updated_at();

drop trigger if exists protect_nota_fiscal_item on public.nota_fiscal_itens;
create trigger protect_nota_fiscal_item
before update on public.nota_fiscal_itens
for each row execute function public.fiscal_protect_nota_fiscal_item();

drop trigger if exists validate_nota_fiscal_itens_total_insert on public.nota_fiscal_itens;
create constraint trigger validate_nota_fiscal_itens_total_insert
after insert on public.nota_fiscal_itens
deferrable initially deferred
for each row execute function public.fiscal_validate_note_items_total_trigger();

drop trigger if exists validate_nota_fiscal_itens_total_update on public.nota_fiscal_itens;
create constraint trigger validate_nota_fiscal_itens_total_update
after update on public.nota_fiscal_itens
deferrable initially deferred
for each row execute function public.fiscal_validate_note_items_total_trigger();

drop trigger if exists validate_nota_fiscal_itens_total_delete on public.nota_fiscal_itens;
create constraint trigger validate_nota_fiscal_itens_total_delete
after delete on public.nota_fiscal_itens
deferrable initially deferred
for each row execute function public.fiscal_validate_note_items_total_trigger();

create index if not exists idx_config_fiscal_unidade_unidade on public.config_fiscal_unidade(unidade_id);
create index if not exists idx_servicos_fiscais_unidade on public.servicos_fiscais(unidade_id);
create index if not exists idx_servicos_fiscais_servico on public.servicos_fiscais(servico_id);
create index if not exists idx_notas_fiscais_unidade_competencia on public.notas_fiscais(unidade_id, data_competencia desc);
create index if not exists idx_notas_fiscais_cliente on public.notas_fiscais(cliente_id);
create index if not exists idx_notas_fiscais_agendamento on public.notas_fiscais(agendamento_id);
create index if not exists idx_notas_fiscais_pacote on public.notas_fiscais(pacote_id);
create index if not exists idx_notas_fiscais_financeiro_movimento on public.notas_fiscais(financeiro_movimento_id);
create index if not exists idx_notas_fiscais_financeiro_pagamento on public.notas_fiscais(financeiro_pagamento_id);
create index if not exists idx_nota_fiscal_itens_nota on public.nota_fiscal_itens(nota_fiscal_id);

create unique index if not exists uq_notas_fiscais_movimento_ativo
on public.notas_fiscais(financeiro_movimento_id)
where status <> 'CANCELADA';

create unique index if not exists uq_notas_fiscais_agendamento_movimento_ativo
on public.notas_fiscais(unidade_id, agendamento_id, financeiro_movimento_id)
where agendamento_id is not null
  and status <> 'CANCELADA';

create unique index if not exists uq_notas_fiscais_pacote_movimento_ativo
on public.notas_fiscais(unidade_id, pacote_id, financeiro_movimento_id)
where pacote_id is not null
  and status <> 'CANCELADA';

insert into public.servicos_fiscais (
  unidade_id,
  servico_id,
  ativo,
  descricao_fiscal,
  codigo_servico_municipal,
  codigo_nbs
)
select
  su.unidade_id,
  su.servico_id,
  true,
  'Prestação de serviços de higiene, embelezamento e cuidados de animais domésticos, incluindo banho, tosa e serviços complementares.',
  '050801',
  '11405600'
from public.servicos_unidade su
join public.unidades u on u.id = su.unidade_id and u.ativo = true
join public.servicos s on s.id = su.servico_id and s.ativo = true
where su.ativo = true
  and (
    lower(s.nome) like '%banho%'
    or lower(s.nome) like '%tosa%'
    or lower(s.nome) like '%hidrat%'
    or lower(s.nome) like '%desembolo%'
    or lower(s.nome) like '%subpelo%'
    or lower(s.nome) like '%escovac%'
    or lower(s.nome) like '%escovaç%'
    or lower(s.nome) like '%dente%'
    or lower(s.nome) like '%unha%'
    or lower(s.nome) like '%patinha%'
    or lower(s.nome) like '%poodle%'
  )
  and lower(s.nome) not like '%taxi%'
  and lower(s.nome) not like '%táxi%'
  and lower(s.nome) not like '%transporte%'
  and lower(s.nome) not like '%desloc%'
  and lower(s.nome) not like '%produto%'
on conflict (unidade_id, servico_id) do nothing;

alter table public.config_fiscal_unidade enable row level security;
alter table public.servicos_fiscais enable row level security;
alter table public.notas_fiscais enable row level security;
alter table public.nota_fiscal_itens enable row level security;

drop policy if exists "config_fiscal_unidade_select_allowed" on public.config_fiscal_unidade;
drop policy if exists "config_fiscal_unidade_insert_master" on public.config_fiscal_unidade;
drop policy if exists "config_fiscal_unidade_update_master" on public.config_fiscal_unidade;
drop policy if exists "config_fiscal_unidade_delete_master" on public.config_fiscal_unidade;

create policy "config_fiscal_unidade_select_allowed"
on public.config_fiscal_unidade for select to authenticated
using (public.fiscal_can_view_config(unidade_id));

create policy "config_fiscal_unidade_insert_master"
on public.config_fiscal_unidade for insert to authenticated
with check (public.fiscal_can_manage_config(unidade_id));

create policy "config_fiscal_unidade_update_master"
on public.config_fiscal_unidade for update to authenticated
using (public.fiscal_can_manage_config(unidade_id))
with check (public.fiscal_can_manage_config(unidade_id));

create policy "config_fiscal_unidade_delete_master"
on public.config_fiscal_unidade for delete to authenticated
using (public.fiscal_can_manage_config(unidade_id));

drop policy if exists "servicos_fiscais_select_allowed" on public.servicos_fiscais;
drop policy if exists "servicos_fiscais_insert_master" on public.servicos_fiscais;
drop policy if exists "servicos_fiscais_update_master" on public.servicos_fiscais;
drop policy if exists "servicos_fiscais_delete_master" on public.servicos_fiscais;

create policy "servicos_fiscais_select_allowed"
on public.servicos_fiscais for select to authenticated
using (public.fiscal_can_view_config(unidade_id));

create policy "servicos_fiscais_insert_master"
on public.servicos_fiscais for insert to authenticated
with check (public.fiscal_can_manage_config(unidade_id));

create policy "servicos_fiscais_update_master"
on public.servicos_fiscais for update to authenticated
using (public.fiscal_can_manage_config(unidade_id))
with check (public.fiscal_can_manage_config(unidade_id));

create policy "servicos_fiscais_delete_master"
on public.servicos_fiscais for delete to authenticated
using (public.fiscal_can_manage_config(unidade_id));

drop policy if exists "notas_fiscais_select_allowed" on public.notas_fiscais;
drop policy if exists "notas_fiscais_update_draft_allowed" on public.notas_fiscais;
drop policy if exists "notas_fiscais_delete_draft_allowed" on public.notas_fiscais;

create policy "notas_fiscais_select_allowed"
on public.notas_fiscais for select to authenticated
using (public.fiscal_can_view_note(unidade_id));

create policy "notas_fiscais_update_draft_allowed"
on public.notas_fiscais for update to authenticated
using (
  public.fiscal_can_edit_draft(unidade_id)
  and status = 'RASCUNHO'
)
with check (
  public.fiscal_can_edit_draft(unidade_id)
  and status = 'RASCUNHO'
);

create policy "notas_fiscais_delete_draft_allowed"
on public.notas_fiscais for delete to authenticated
using (
  status = 'RASCUNHO'
  and public.fiscal_can_delete_draft(unidade_id)
);

drop policy if exists "nota_fiscal_itens_select_allowed" on public.nota_fiscal_itens;
drop policy if exists "nota_fiscal_itens_update_draft_allowed" on public.nota_fiscal_itens;
drop policy if exists "nota_fiscal_itens_delete_draft_allowed" on public.nota_fiscal_itens;

create policy "nota_fiscal_itens_select_allowed"
on public.nota_fiscal_itens for select to authenticated
using (
  exists (
    select 1 from public.notas_fiscais nf
    where nf.id = nota_fiscal_itens.nota_fiscal_id
      and public.fiscal_can_view_note(nf.unidade_id)
  )
);

create policy "nota_fiscal_itens_update_draft_allowed"
on public.nota_fiscal_itens for update to authenticated
using (
  exists (
    select 1 from public.notas_fiscais nf
    where nf.id = nota_fiscal_itens.nota_fiscal_id
      and nf.status = 'RASCUNHO'
      and public.fiscal_can_edit_draft(nf.unidade_id)
  )
)
with check (
  exists (
    select 1 from public.notas_fiscais nf
    where nf.id = nota_fiscal_itens.nota_fiscal_id
      and nf.status = 'RASCUNHO'
      and public.fiscal_can_edit_draft(nf.unidade_id)
  )
);

grant select, insert, update, delete on public.config_fiscal_unidade to authenticated;
grant select, insert, update, delete on public.servicos_fiscais to authenticated;
grant select, update, delete on public.notas_fiscais to authenticated;
grant select, update on public.nota_fiscal_itens to authenticated;
revoke insert, delete on public.nota_fiscal_itens from authenticated;

revoke execute on function public.fiscal_safe_audit(bigint, text, text, bigint, text, jsonb, jsonb) from public;
revoke execute on function public.criar_rascunho_fiscal_por_movimento(bigint) from public;
revoke execute on function public.criar_rascunho_fiscal_por_movimento(bigint) from anon;
grant execute on function public.criar_rascunho_fiscal_por_movimento(bigint) to authenticated;

commit;
