-- Catalogo de modelos de pacote (ex: "Semanal R$160", "Quinzenal R$100"),
-- gerenciado em Configuracoes e usado para preencher automaticamente o
-- formulario de criacao de pacote em Pacotes.tsx. Espelha o padrao
-- servicos/servicos_unidade (catalogo global + disponibilidade por unidade).

create table if not exists public.catalogo_pacotes (
  id bigint primary key generated by default as identity,
  nome text not null,
  frequencia text not null check (frequencia in ('Weekly','Bi-weekly')),
  qtd_sessoes integer not null default 4 check (qtd_sessoes > 0),
  valor_base numeric(10,2) not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.catalogo_pacotes_unidade (
  id bigint primary key generated by default as identity,
  unidade_id bigint not null references public.unidades(id) on delete cascade,
  catalogo_pacote_id bigint not null references public.catalogo_pacotes(id) on delete cascade,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  unique (unidade_id, catalogo_pacote_id)
);

alter table public.pacotes
  add column if not exists valor_desconto numeric(10,2) not null default 0,
  add column if not exists catalogo_pacote_id bigint references public.catalogo_pacotes(id) on delete set null;

alter table public.catalogo_pacotes enable row level security;
alter table public.catalogo_pacotes_unidade enable row level security;

create policy "catalogo_pacotes_read_authenticated"
on public.catalogo_pacotes for select to authenticated using (true);

create policy "catalogo_pacotes_master_write"
on public.catalogo_pacotes for all to authenticated
using (public.is_master()) with check (public.is_master());

create policy "catalogo_pacotes_unidade_unit_access"
on public.catalogo_pacotes_unidade for all to authenticated
using (public.can_access_unidade(unidade_id)) with check (public.can_access_unidade(unidade_id));
