-- Modulo de Rentabilidade (markup e margem por servico e pacote).
-- Migration aditiva: nenhuma tabela/coluna existente e alterada de forma
-- destrutiva. servicos.custo_padrao permanece como esta (vira apenas um
-- cache do custo vigente, mantido por trigger) para nao quebrar nada que
-- ja leia essa coluna.
--
-- Fonte unica de custo a partir de agora: servico_custo_historico (custo
-- por servico, versionado por data) e custo_transporte_historico (custo
-- por viagem de taxi dog, versionado por data). fn_dashboard_custos_pacotes
-- (migration 0032) e reescrita no fim deste arquivo para ler dessa mesma
-- fonte, eliminando a divergencia entre Dashboard e Rentabilidade.

-- ---------------------------------------------------------------------------
-- 1) Historico de custo por servico
-- ---------------------------------------------------------------------------
create table if not exists public.servico_custo_historico (
  id bigint primary key generated by default as identity,
  servico_id bigint not null references public.servicos(id) on delete cascade,
  custo_insumos numeric(10,2),
  custo_mao_obra numeric(10,2),
  custo_outros numeric(10,2),
  custo_total numeric(10,2) not null,
  vigente_desde date not null default current_date,
  observacao text,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references auth.users(id) on delete set null
);

create index if not exists idx_servico_custo_historico_servico_data
  on public.servico_custo_historico(servico_id, vigente_desde desc);

-- Backfill: 1 registro por servico existente, vigente desde uma data
-- bem antiga, usando o custo_padrao atual (garante que fn_custo_servico_em
-- nunca retorna null para servicos ja cadastrados).
insert into public.servico_custo_historico (servico_id, custo_total, vigente_desde, observacao)
select s.id, coalesce(s.custo_padrao, 0), date '2000-01-01', 'Backfill automatico da migration 0035'
from public.servicos s
where not exists (
  select 1 from public.servico_custo_historico h where h.servico_id = s.id
);

-- ---------------------------------------------------------------------------
-- 2) Historico de custo de transporte/taxi dog (por viagem)
-- ---------------------------------------------------------------------------
create table if not exists public.custo_transporte_historico (
  id bigint primary key generated by default as identity,
  custo_combustivel numeric(10,2),
  custo_tempo numeric(10,2),
  custo_total numeric(10,2) not null,
  vigente_desde date not null default current_date,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references auth.users(id) on delete set null
);

create index if not exists idx_custo_transporte_historico_data
  on public.custo_transporte_historico(vigente_desde desc);

insert into public.custo_transporte_historico (custo_total, vigente_desde)
select 0, date '2000-01-01'
where not exists (select 1 from public.custo_transporte_historico);

-- ---------------------------------------------------------------------------
-- 3) Thresholds de margem (linha unica, mesmo padrao de config_sistema)
-- ---------------------------------------------------------------------------
create table if not exists public.rentabilidade_config (
  id bigint primary key default 1,
  margem_verde_min numeric(5,2) not null default 60,
  margem_amarela_min numeric(5,2) not null default 30,
  updated_at timestamptz not null default now(),
  constraint rentabilidade_config_singleton check (id = 1)
);

insert into public.rentabilidade_config (id)
select 1
where not exists (select 1 from public.rentabilidade_config where id = 1);

-- ---------------------------------------------------------------------------
-- 4) custo_padrao vira cache do custo vigente (compat. com codigo legado
--    que ainda leia essa coluna diretamente).
-- ---------------------------------------------------------------------------
create or replace function public.fn_sync_custo_padrao()
returns trigger
language plpgsql
as $$
begin
  update public.servicos
  set custo_padrao = coalesce((
    select h.custo_total
    from public.servico_custo_historico h
    where h.servico_id = new.servico_id
      and h.vigente_desde <= current_date
    order by h.vigente_desde desc
    limit 1
  ), 0)
  where id = new.servico_id;
  return new;
end;
$$;

drop trigger if exists trg_sync_custo_padrao on public.servico_custo_historico;
create trigger trg_sync_custo_padrao
after insert on public.servico_custo_historico
for each row execute function public.fn_sync_custo_padrao();

-- ---------------------------------------------------------------------------
-- 5) Helpers de leitura: custo vigente numa data (usa sempre a ultima linha
--    com vigente_desde <= data do evento, para relatorios antigos nao
--    mudarem retroativamente quando o custo atual e alterado).
-- ---------------------------------------------------------------------------
create or replace function public.fn_custo_servico_em(p_servico_id bigint, p_data date)
returns numeric
language sql
stable
as $$
  select coalesce(
    (
      select h.custo_total
      from public.servico_custo_historico h
      where h.servico_id = p_servico_id
        and h.vigente_desde <= coalesce(p_data, current_date)
      order by h.vigente_desde desc
      limit 1
    ),
    0
  );
$$;

create or replace function public.fn_custo_transporte_em(p_data date)
returns numeric
language sql
stable
as $$
  select coalesce(
    (
      select h.custo_total
      from public.custo_transporte_historico h
      where h.vigente_desde <= coalesce(p_data, current_date)
      order by h.vigente_desde desc
      limit 1
    ),
    0
  );
$$;

-- ---------------------------------------------------------------------------
-- 6) RLS: leitura liberada para autenticados, escrita restrita a master
--    (mesmo padrao de catalogo_pacotes, migration 0026).
-- ---------------------------------------------------------------------------
alter table public.servico_custo_historico enable row level security;
alter table public.custo_transporte_historico enable row level security;
alter table public.rentabilidade_config enable row level security;

create policy "servico_custo_historico_read_authenticated"
on public.servico_custo_historico for select to authenticated using (true);
create policy "servico_custo_historico_master_write"
on public.servico_custo_historico for all to authenticated
using (public.is_master()) with check (public.is_master());

create policy "custo_transporte_historico_read_authenticated"
on public.custo_transporte_historico for select to authenticated using (true);
create policy "custo_transporte_historico_master_write"
on public.custo_transporte_historico for all to authenticated
using (public.is_master()) with check (public.is_master());

create policy "rentabilidade_config_read_authenticated"
on public.rentabilidade_config for select to authenticated using (true);
create policy "rentabilidade_config_master_write"
on public.rentabilidade_config for all to authenticated
using (public.is_master()) with check (public.is_master());

-- ---------------------------------------------------------------------------
-- 7) fn_dashboard_custos_pacotes (migration 0032) reescrita para usar a
--    fonte unica de custo (fn_custo_servico_em) em vez de custo_padrao
--    direto. Mesma assinatura e mesmas colunas de retorno: zero mudanca no
--    frontend do Dashboard (services/dashboardGerencial.ts), so a fonte do
--    dado por tras muda.
-- ---------------------------------------------------------------------------
create or replace function public.fn_dashboard_custos_pacotes(
  p_unidade_id bigint,
  p_data_inicio date,
  p_data_fim date,
  p_transporte text default 'todos'
)
returns table (servico text, qtd bigint, custo_unitario numeric, custo_total numeric)
language sql
stable
as $$
  with itens as (
    select
      s.nome as servico,
      public.fn_custo_servico_em(s.id, (a.data_fim_real at time zone 'America/Sao_Paulo')::date) as custo
    from public.agendamentos a
    join public.agendamento_itens ai on ai.agendamento_id = a.id and ai.tipo = 'principal'
    join public.servicos s on s.id = ai.servico_id
    where a.pacote_id is not null
      and a.status = 'Finalizado'
      and a.data_fim_real is not null
      and (p_unidade_id is null or a.unidade_id = p_unidade_id)
      and (p_transporte = 'todos' or (p_transporte = 'com' and a.tem_taxi = true) or (p_transporte = 'sem' and a.tem_taxi = false))
      and ((a.data_fim_real at time zone 'America/Sao_Paulo')::date) between p_data_inicio and p_data_fim
  )
  select servico, count(*) as qtd, avg(custo) as custo_unitario, sum(custo) as custo_total
  from itens
  group by servico
  order by custo_total desc;
$$;

-- ---------------------------------------------------------------------------
-- 8) RPCs da tela Rentabilidade
-- ---------------------------------------------------------------------------

-- 8.1 Rentabilidade por servico (avulso "principal" + "adicional" itemizado).
-- Sessoes de pacote ficam de fora daqui (nao tem preco individual real: a
-- receita do pacote e reconhecida pelo valor do pacote inteiro, nunca pela
-- soma dos servicos). Ver fn_rentabilidade_pacotes para a rentabilidade de
-- pacotes.
create or replace function public.fn_rentabilidade_servicos(
  p_unidade_id bigint,
  p_data_inicio date,
  p_data_fim date
)
returns table (
  servico_id bigint,
  servico text,
  qtd bigint,
  preco_medio numeric,
  custo_medio numeric,
  receita_total numeric,
  custo_total numeric,
  lucro_total numeric
)
language sql
stable
as $$
  -- Nota: agendamento_itens.valor e sempre gravado como 0 para itens
  -- "principal" pelo app atual (Appointments.tsx / AgendamentoDetalhesModal.tsx)
  -- - o preco real fica em agendamentos.valor_total. Por isso o preco de cada
  -- item principal e derivado de (valor_total + valor_pagamento_2 - valor_transporte)
  -- dividido igualmente entre os itens principais do mesmo agendamento (mesma
  -- formula de "valor_servico" usada em fn_receita_eventos, migration 0032,
  -- para o Dashboard/Financeiro nao divergir deste calculo).
  with qtd_principal as (
    select agendamento_id, count(*) as qtd_itens
    from public.agendamento_itens
    where tipo = 'principal'
    group by agendamento_id
  ),
  itens as (
    select
      s.id as servico_id,
      s.nome as servico,
      ((coalesce(a.valor_total, 0) + coalesce(a.valor_pagamento_2, 0) - coalesce(a.valor_transporte, 0))
        / nullif(qp.qtd_itens, 0)) as valor,
      public.fn_custo_servico_em(s.id, (a.data_fim_real at time zone 'America/Sao_Paulo')::date) as custo
    from public.agendamento_itens ai
    join public.agendamentos a on a.id = ai.agendamento_id
    join public.servicos s on s.id = ai.servico_id
    join qtd_principal qp on qp.agendamento_id = a.id
    where ai.tipo = 'principal'
      and a.pacote_id is null
      and a.status = 'Finalizado'
      and a.data_fim_real is not null
      and (p_unidade_id is null or a.unidade_id = p_unidade_id)
      and ((a.data_fim_real at time zone 'America/Sao_Paulo')::date) between p_data_inicio and p_data_fim

    union all

    select
      s.id as servico_id,
      s.nome as servico,
      ai.valor as valor,
      public.fn_custo_servico_em(s.id, a.data_pagamento_extra) as custo
    from public.agendamento_itens ai
    join public.agendamentos a on a.id = ai.agendamento_id
    join public.servicos s on s.id = ai.servico_id
    where ai.tipo = 'adicional'
      and a.status_pagamento_extra = 'PAGO'
      and a.data_pagamento_extra is not null
      and (p_unidade_id is null or a.unidade_id = p_unidade_id)
      and a.data_pagamento_extra between p_data_inicio and p_data_fim
  )
  select
    servico_id,
    servico,
    count(*) as qtd,
    avg(valor) as preco_medio,
    avg(custo) as custo_medio,
    sum(valor) as receita_total,
    sum(custo) as custo_total,
    sum(valor - custo) as lucro_total
  from itens
  group by servico_id, servico
  order by lucro_total desc;
$$;

-- 8.2 Rentabilidade por pacote: agrupado por tipo de pacote (catalogo_pacote_id).
-- Regra critica reaproveitada de fn_receita_eventos (migration 0032): vale o
-- valor do pacote, nunca a soma dos servicos. Custo projetado = custo
-- vigente do servico (na data do pagamento) x sessoes contratadas, + custo
-- de transporte (mesma premissa: 1 viagem por sessao) quando o pacote inclui
-- taxi dog (valor_transporte > 0).
create or replace function public.fn_rentabilidade_pacotes(
  p_unidade_id bigint,
  p_data_inicio date,
  p_data_fim date
)
returns table (
  catalogo_pacote_id bigint,
  pacote_nome text,
  qtd_pacotes bigint,
  qtd_sessoes_media numeric,
  preco_medio numeric,
  custo_medio numeric,
  receita_total numeric,
  custo_total numeric,
  lucro_total numeric,
  valor_efetivo_sessao_medio numeric,
  servico_id bigint,
  servico_nome text
)
language sql
stable
as $$
  with base as (
    select
      p.id,
      coalesce(p.catalogo_pacote_id, -p.id) as grupo_id,
      coalesce(cp.nome, p.nome, p.nome_pacote, 'Pacote sem nome') as nome,
      p.qtd_sessoes,
      (p.valor_total + p.valor_pagamento_2) as preco,
      p.valor_total as valor_servico,
      (p.qtd_sessoes * public.fn_custo_servico_em(p.servico_id, p.data_pagamento)) as custo_sessoes,
      case when p.valor_transporte > 0
        then p.qtd_sessoes * public.fn_custo_transporte_em(p.data_pagamento)
        else 0
      end as custo_transporte,
      p.servico_id
    from public.pacotes p
    left join public.catalogo_pacotes cp on cp.id = p.catalogo_pacote_id
    where p.pago = true
      and p.data_pagamento is not null
      and (p_unidade_id is null or p.unidade_id = p_unidade_id)
      and p.data_pagamento between p_data_inicio and p_data_fim
  ),
  agg as (
    select
      b.grupo_id,
      b.nome,
      count(*) as qtd_pacotes,
      avg(b.qtd_sessoes) as qtd_sessoes_media,
      avg(b.preco) as preco_medio,
      avg(b.custo_sessoes + b.custo_transporte) as custo_medio,
      sum(b.preco) as receita_total,
      sum(b.custo_sessoes + b.custo_transporte) as custo_total,
      sum(b.preco - b.custo_sessoes - b.custo_transporte) as lucro_total,
      avg(case when b.qtd_sessoes > 0 then b.valor_servico / b.qtd_sessoes else null end) as valor_efetivo_sessao_medio,
      -- servico predominante do grupo, para comparar com o preco avulso
      -- equivalente (fn_rentabilidade_servicos) na tela de Rentabilidade.
      mode() within group (order by b.servico_id) as servico_id
    from base b
    group by b.grupo_id, b.nome
  )
  select
    case when a.grupo_id < 0 then null else a.grupo_id end as catalogo_pacote_id,
    a.nome as pacote_nome,
    a.qtd_pacotes,
    a.qtd_sessoes_media,
    a.preco_medio,
    a.custo_medio,
    a.receita_total,
    a.custo_total,
    a.lucro_total,
    a.valor_efetivo_sessao_medio,
    a.servico_id,
    s.nome as servico_nome
  from agg a
  left join public.servicos s on s.id = a.servico_id
  order by a.lucro_total desc;
$$;

-- 8.3 Resumo do periodo (Bloco A): reaproveita as duas funcoes acima e soma
-- o custo de transporte avulso (viagens fora de pacote) para nao ficar de
-- fora do "custo total" do periodo.
create or replace function public.fn_rentabilidade_resumo(
  p_unidade_id bigint,
  p_data_inicio date,
  p_data_fim date
)
returns jsonb
language plpgsql
stable
as $$
declare
  v_receita_servicos numeric;
  v_custo_servicos numeric;
  v_receita_pacotes numeric;
  v_custo_pacotes numeric;
  v_custo_transporte_avulso numeric;
  v_receita_total numeric;
  v_custo_total numeric;
  v_lucro_total numeric;
  v_margem_media numeric;
  v_markup_medio numeric;
begin
  select coalesce(sum(receita_total), 0), coalesce(sum(custo_total), 0)
    into v_receita_servicos, v_custo_servicos
  from public.fn_rentabilidade_servicos(p_unidade_id, p_data_inicio, p_data_fim);

  select coalesce(sum(receita_total), 0), coalesce(sum(custo_total), 0)
    into v_receita_pacotes, v_custo_pacotes
  from public.fn_rentabilidade_pacotes(p_unidade_id, p_data_inicio, p_data_fim);

  select coalesce(sum(public.fn_custo_transporte_em((a.data_fim_real at time zone 'America/Sao_Paulo')::date)), 0)
    into v_custo_transporte_avulso
  from public.agendamentos a
  where a.tem_taxi = true
    and a.pacote_id is null
    and a.status = 'Finalizado'
    and a.data_fim_real is not null
    and (p_unidade_id is null or a.unidade_id = p_unidade_id)
    and ((a.data_fim_real at time zone 'America/Sao_Paulo')::date) between p_data_inicio and p_data_fim;

  v_receita_total := v_receita_servicos + v_receita_pacotes;
  v_custo_total := v_custo_servicos + v_custo_pacotes + v_custo_transporte_avulso;
  v_lucro_total := v_receita_total - v_custo_total;
  v_margem_media := case when v_receita_total > 0 then (v_lucro_total / v_receita_total) * 100 else 0 end;
  v_markup_medio := case when v_custo_total > 0 then v_receita_total / v_custo_total else 0 end;

  return jsonb_build_object(
    'receita_total', v_receita_total,
    'custo_total', v_custo_total,
    'lucro_total', v_lucro_total,
    'margem_media_pct', v_margem_media,
    'markup_medio', v_markup_medio
  );
end;
$$;
