-- Modulo de Gestao de Gastos (despesas fixas/variaveis, contas recorrentes,
-- folha de pagamento) + integracao com Financeiro Geral e Rentabilidade.
-- Migration aditiva: `despesas` e evoluida via ALTER (nao recriada), nenhuma
-- tabela/funcao existente e removida. `financeiro_movimentos` (ledger de
-- receita/fiscal) NAO e tocado.
--
-- Decisoes confirmadas com o dono do produto:
--  - Backfill das despesas antigas: status='pago', tipo='variavel',
--    categoria='Outros', data_pagamento = data_despesa (preserva os numeros
--    ja usados hoje no Financeiro Geral).
--  - Custo de transporte a partir de combustivel real: SUGESTAO editavel em
--    Configuracoes -> Custos dos Servicos, nunca sobrescreve
--    custo_transporte_historico sozinho (mesmo padrao da mao de obra).
--  - Categorias de despesa: gerenciadas via modal dentro da propria tela
--    Gastos (nao uma aba nova em Configuracoes).

-- ---------------------------------------------------------------------------
-- 1) Categorias de despesa (seed fixo, editavel depois)
-- ---------------------------------------------------------------------------
create table if not exists public.categorias_despesa (
  id bigint primary key generated by default as identity,
  nome text not null unique,
  icone text not null default 'fa-circle-dollar-to-slot',
  cor text not null default '#94A3B8',
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.categorias_despesa (nome, icone, cor) values
  ('Folha de pagamento', 'fa-users', '#7C3AED'),
  ('Aluguel', 'fa-building', '#F59E0B'),
  ('Utilidades', 'fa-bolt', '#0EA5E9'),
  ('Combustível/Transporte', 'fa-gas-pump', '#10B981'),
  ('Insumos', 'fa-boxes-stacked', '#EC4899'),
  ('Manutenção', 'fa-screwdriver-wrench', '#F43F5E'),
  ('Marketing', 'fa-bullhorn', '#8B5CF6'),
  ('Comunicação', 'fa-phone', '#06B6D4'),
  ('Sistema/Assinaturas', 'fa-laptop', '#6366F1'),
  ('Impostos', 'fa-landmark', '#DC2626'),
  ('Outros', 'fa-ellipsis', '#94A3B8')
on conflict (nome) do nothing;

alter table public.categorias_despesa enable row level security;

create policy "categorias_despesa_read_authenticated"
on public.categorias_despesa for select to authenticated using (true);
create policy "categorias_despesa_master_write"
on public.categorias_despesa for all to authenticated
using (public.is_master()) with check (public.is_master());

-- ---------------------------------------------------------------------------
-- 2) Evolucao aditiva de `despesas` (ALTER; nao recria a tabela)
-- ---------------------------------------------------------------------------
alter table public.despesas
  add column if not exists categoria_id bigint references public.categorias_despesa(id) on delete set null,
  add column if not exists tipo text not null default 'variavel' check (tipo in ('fixo','variavel')),
  add column if not exists forma_pagamento text,
  add column if not exists status text not null default 'pago' check (status in ('pago','pendente')),
  add column if not exists data_vencimento date,
  add column if not exists data_pagamento date,
  add column if not exists conta_recorrente_id bigint,
  add column if not exists litros numeric(10,2),
  add column if not exists km_rodado numeric(10,2);

create index if not exists idx_despesas_status_data_pagamento
  on public.despesas(unidade_id, status, data_pagamento);
create index if not exists idx_despesas_categoria
  on public.despesas(categoria_id);

-- Backfill: preserva o comportamento historico do Financeiro Geral.
update public.despesas
set data_pagamento = data_despesa
where data_pagamento is null;

update public.despesas
set categoria_id = (select id from public.categorias_despesa where nome = 'Outros')
where categoria_id is null;

-- ---------------------------------------------------------------------------
-- 3) Contas fixas recorrentes (modelos que geram pendencias mensais)
-- ---------------------------------------------------------------------------
create table if not exists public.contas_fixas_recorrentes (
  id bigint primary key generated by default as identity,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  categoria_id bigint references public.categorias_despesa(id) on delete set null,
  descricao text not null,
  dia_vencimento int not null check (dia_vencimento between 1 and 28),
  valor_previsto numeric(10,2) not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_contas_fixas_unidade_ativo
  on public.contas_fixas_recorrentes(unidade_id, ativo);

alter table public.despesas
  add constraint despesas_conta_recorrente_fk foreign key (conta_recorrente_id)
  references public.contas_fixas_recorrentes(id) on delete set null;

alter table public.contas_fixas_recorrentes enable row level security;
create policy "contas_fixas_recorrentes_unit_access"
on public.contas_fixas_recorrentes for all to authenticated
using (public.can_access_unidade(unidade_id)) with check (public.can_access_unidade(unidade_id));

create trigger set_contas_fixas_recorrentes_updated_at
before update on public.contas_fixas_recorrentes
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- 4) Folha de pagamento (detalhamento por funcionario; espelha 1 despesa)
-- ---------------------------------------------------------------------------
create table if not exists public.folha_pagamento (
  id bigint primary key generated by default as identity,
  funcionario_id bigint not null references public.funcionarios(id) on delete restrict,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  competencia date not null,
  salario numeric(10,2) not null default 0,
  adiantamento numeric(10,2) not null default 0,
  encargos numeric(10,2) not null default 0,
  data_pagamento date,
  forma_pagamento text,
  despesa_id bigint references public.despesas(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_folha_pagamento_unidade_competencia
  on public.folha_pagamento(unidade_id, competencia);

alter table public.folha_pagamento enable row level security;
create policy "folha_pagamento_unit_access"
on public.folha_pagamento for all to authenticated
using (public.can_access_unidade(unidade_id)) with check (public.can_access_unidade(unidade_id));

create trigger set_folha_pagamento_updated_at
before update on public.folha_pagamento
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- 5) Geracao idempotente de pendencias a partir das contas fixas recorrentes.
--    Chamada pelo frontend ao abrir a tela Gastos (nao ha pg_cron no projeto).
--    So insere se ainda nao existir uma despesa daquela conta_recorrente_id
--    no mes de referencia.
-- ---------------------------------------------------------------------------
create or replace function public.fn_gerar_despesas_recorrentes(p_unidade_id bigint, p_referencia date)
returns int
language plpgsql
as $$
declare
  v_conta record;
  v_vencimento date;
  v_criadas int := 0;
begin
  for v_conta in
    select * from public.contas_fixas_recorrentes
    where ativo = true
      and (p_unidade_id is null or unidade_id = p_unidade_id)
  loop
    v_vencimento := make_date(
      extract(year from p_referencia)::int,
      extract(month from p_referencia)::int,
      v_conta.dia_vencimento
    );

    if not exists (
      select 1 from public.despesas d
      where d.conta_recorrente_id = v_conta.id
        and date_trunc('month', d.data_vencimento) = date_trunc('month', v_vencimento)
    ) then
      insert into public.despesas (
        unidade_id, nome_item, descricao, quantidade, valor_total, data_despesa,
        categoria_id, tipo, status, data_vencimento, conta_recorrente_id
      ) values (
        v_conta.unidade_id, v_conta.descricao, 'Gerado automaticamente pela conta fixa recorrente', 1,
        v_conta.valor_previsto, v_vencimento, v_conta.categoria_id, 'fixo', 'pendente', v_vencimento, v_conta.id
      );
      v_criadas := v_criadas + 1;
    end if;
  end loop;

  return v_criadas;
end;
$$;

-- ---------------------------------------------------------------------------
-- 6) RPCs de leitura da tela Gastos (mesmo padrao de fn_dashboard_*): todas
--    filtram status='pago' e data_pagamento no periodo -- pendencias aparecem
--    so nos cards de Proximos Vencimentos / Contas Fixas, nao nos KPIs.
-- ---------------------------------------------------------------------------
create or replace function public.fn_gastos_kpis(
  p_unidade_id bigint,
  p_data_inicio date,
  p_data_fim date,
  p_data_inicio_ant date,
  p_data_fim_ant date
)
returns jsonb
language plpgsql
stable
as $$
declare
  v_total_atual numeric; v_total_anterior numeric;
  v_fixos_atual numeric; v_fixos_anterior numeric;
  v_variaveis_atual numeric; v_variaveis_anterior numeric;
  v_folha_atual numeric; v_folha_anterior numeric;
  v_combustivel_atual numeric; v_combustivel_anterior numeric;
  v_insumos_manutencao_atual numeric; v_insumos_manutencao_anterior numeric;
begin
  select coalesce(sum(d.valor_total), 0) into v_total_atual
  from public.despesas d
  where (p_unidade_id is null or d.unidade_id = p_unidade_id)
    and d.status = 'pago' and d.data_pagamento between p_data_inicio and p_data_fim;

  select coalesce(sum(d.valor_total), 0) into v_total_anterior
  from public.despesas d
  where (p_unidade_id is null or d.unidade_id = p_unidade_id)
    and d.status = 'pago' and d.data_pagamento between p_data_inicio_ant and p_data_fim_ant;

  select coalesce(sum(d.valor_total) filter (where d.tipo = 'fixo'), 0),
         coalesce(sum(d.valor_total) filter (where d.tipo = 'variavel'), 0)
    into v_fixos_atual, v_variaveis_atual
  from public.despesas d
  where (p_unidade_id is null or d.unidade_id = p_unidade_id)
    and d.status = 'pago' and d.data_pagamento between p_data_inicio and p_data_fim;

  select coalesce(sum(d.valor_total) filter (where d.tipo = 'fixo'), 0),
         coalesce(sum(d.valor_total) filter (where d.tipo = 'variavel'), 0)
    into v_fixos_anterior, v_variaveis_anterior
  from public.despesas d
  where (p_unidade_id is null or d.unidade_id = p_unidade_id)
    and d.status = 'pago' and d.data_pagamento between p_data_inicio_ant and p_data_fim_ant;

  select coalesce(sum(d.valor_total) filter (where c.nome = 'Folha de pagamento'), 0),
         coalesce(sum(d.valor_total) filter (where c.nome = 'Combustível/Transporte'), 0),
         coalesce(sum(d.valor_total) filter (where c.nome in ('Insumos', 'Manutenção')), 0)
    into v_folha_atual, v_combustivel_atual, v_insumos_manutencao_atual
  from public.despesas d
  left join public.categorias_despesa c on c.id = d.categoria_id
  where (p_unidade_id is null or d.unidade_id = p_unidade_id)
    and d.status = 'pago' and d.data_pagamento between p_data_inicio and p_data_fim;

  select coalesce(sum(d.valor_total) filter (where c.nome = 'Folha de pagamento'), 0),
         coalesce(sum(d.valor_total) filter (where c.nome = 'Combustível/Transporte'), 0),
         coalesce(sum(d.valor_total) filter (where c.nome in ('Insumos', 'Manutenção')), 0)
    into v_folha_anterior, v_combustivel_anterior, v_insumos_manutencao_anterior
  from public.despesas d
  left join public.categorias_despesa c on c.id = d.categoria_id
  where (p_unidade_id is null or d.unidade_id = p_unidade_id)
    and d.status = 'pago' and d.data_pagamento between p_data_inicio_ant and p_data_fim_ant;

  return jsonb_build_object(
    'total_atual', v_total_atual, 'total_anterior', v_total_anterior,
    'fixos_atual', v_fixos_atual, 'fixos_anterior', v_fixos_anterior,
    'variaveis_atual', v_variaveis_atual, 'variaveis_anterior', v_variaveis_anterior,
    'folha_atual', v_folha_atual, 'folha_anterior', v_folha_anterior,
    'combustivel_atual', v_combustivel_atual, 'combustivel_anterior', v_combustivel_anterior,
    'insumos_manutencao_atual', v_insumos_manutencao_atual, 'insumos_manutencao_anterior', v_insumos_manutencao_anterior
  );
end;
$$;

create or replace function public.fn_gastos_evolucao(
  p_unidade_id bigint,
  p_data_inicio date,
  p_data_fim date,
  p_granularidade text default 'dia'
)
returns table (bucket date, valor numeric)
language sql
stable
as $$
  select
    case p_granularidade
      when 'semana' then date_trunc('week', d.data_pagamento)::date
      when 'mes' then date_trunc('month', d.data_pagamento)::date
      else d.data_pagamento
    end as bucket,
    sum(d.valor_total) as valor
  from public.despesas d
  where (p_unidade_id is null or d.unidade_id = p_unidade_id)
    and d.status = 'pago'
    and d.data_pagamento between p_data_inicio and p_data_fim
  group by 1
  order by 1;
$$;

create or replace function public.fn_gastos_por_categoria(
  p_unidade_id bigint,
  p_data_inicio date,
  p_data_fim date
)
returns table (categoria_id bigint, categoria_nome text, icone text, cor text, valor numeric)
language sql
stable
as $$
  select c.id as categoria_id, c.nome as categoria_nome, c.icone, c.cor, sum(d.valor_total) as valor
  from public.despesas d
  join public.categorias_despesa c on c.id = d.categoria_id
  where (p_unidade_id is null or d.unidade_id = p_unidade_id)
    and d.status = 'pago'
    and d.data_pagamento between p_data_inicio and p_data_fim
  group by c.id, c.nome, c.icone, c.cor
  order by valor desc;
$$;

create or replace function public.fn_gastos_combustivel_resumo(
  p_unidade_id bigint,
  p_data_inicio date,
  p_data_fim date
)
returns jsonb
language plpgsql
stable
as $$
declare
  v_litros numeric;
  v_km numeric;
  v_custo numeric;
begin
  select coalesce(sum(d.litros), 0), coalesce(sum(d.km_rodado), 0), coalesce(sum(d.valor_total), 0)
    into v_litros, v_km, v_custo
  from public.despesas d
  join public.categorias_despesa c on c.id = d.categoria_id
  where (p_unidade_id is null or d.unidade_id = p_unidade_id)
    and d.status = 'pago'
    and d.data_pagamento between p_data_inicio and p_data_fim
    and c.nome = 'Combustível/Transporte';

  return jsonb_build_object(
    'litros_total', v_litros,
    'km_total', v_km,
    'custo_total', v_custo,
    'custo_medio_km', case when v_km > 0 then v_custo / v_km else 0 end
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- 7) Sugestoes para Rentabilidade (nunca sobrescrevem os custos vigentes
--    sozinhas; a tela de Custos dos Servicos exibe e o usuario aplica).
-- ---------------------------------------------------------------------------

-- 7.1 Custo de mao de obra sugerido = (salario + encargos) da folha do mes /
--     qtd de servicos realizados no mesmo mes (mesma contagem de
--     fn_rentabilidade_servicos: principal avulso + adicional pago).
create or replace function public.fn_custo_mao_obra_sugerido(p_unidade_id bigint, p_ano_mes date)
returns numeric
language plpgsql
stable
as $$
declare
  v_folha numeric;
  v_qtd_servicos bigint;
  v_mes_inicio date := date_trunc('month', p_ano_mes)::date;
  v_mes_fim date := (date_trunc('month', p_ano_mes) + interval '1 month' - interval '1 day')::date;
begin
  select coalesce(sum(f.salario + f.encargos), 0) into v_folha
  from public.folha_pagamento f
  where (p_unidade_id is null or f.unidade_id = p_unidade_id)
    and date_trunc('month', f.competencia) = v_mes_inicio;

  select count(*) into v_qtd_servicos
  from (
    select 1
    from public.agendamento_itens ai
    join public.agendamentos a on a.id = ai.agendamento_id
    where ai.tipo = 'principal'
      and a.pacote_id is null
      and a.status = 'Finalizado'
      and a.data_fim_real is not null
      and (p_unidade_id is null or a.unidade_id = p_unidade_id)
      and ((a.data_fim_real at time zone 'America/Sao_Paulo')::date) between v_mes_inicio and v_mes_fim

    union all

    select 1
    from public.agendamento_itens ai
    join public.agendamentos a on a.id = ai.agendamento_id
    where ai.tipo = 'adicional'
      and a.status_pagamento_extra = 'PAGO'
      and a.data_pagamento_extra is not null
      and (p_unidade_id is null or a.unidade_id = p_unidade_id)
      and a.data_pagamento_extra between v_mes_inicio and v_mes_fim
  ) itens;

  return case when v_qtd_servicos > 0 then round(v_folha / v_qtd_servicos, 2) else 0 end;
end;
$$;

-- 7.2 Custo de transporte por viagem sugerido = total gasto com combustivel
--     no mes / qtd de viagens (tem_taxi) finalizadas no mesmo mes.
create or replace function public.fn_custo_transporte_sugerido(p_unidade_id bigint, p_ano_mes date)
returns numeric
language plpgsql
stable
as $$
declare
  v_combustivel numeric;
  v_qtd_viagens bigint;
  v_mes_inicio date := date_trunc('month', p_ano_mes)::date;
  v_mes_fim date := (date_trunc('month', p_ano_mes) + interval '1 month' - interval '1 day')::date;
begin
  select coalesce(sum(d.valor_total), 0) into v_combustivel
  from public.despesas d
  join public.categorias_despesa c on c.id = d.categoria_id
  where (p_unidade_id is null or d.unidade_id = p_unidade_id)
    and d.status = 'pago'
    and c.nome = 'Combustível/Transporte'
    and d.data_pagamento between v_mes_inicio and v_mes_fim;

  select count(*) into v_qtd_viagens
  from public.agendamentos a
  where a.tem_taxi = true
    and a.status = 'Finalizado'
    and a.data_fim_real is not null
    and (p_unidade_id is null or a.unidade_id = p_unidade_id)
    and ((a.data_fim_real at time zone 'America/Sao_Paulo')::date) between v_mes_inicio and v_mes_fim;

  return case when v_qtd_viagens > 0 then round(v_combustivel / v_qtd_viagens, 2) else 0 end;
end;
$$;

-- ---------------------------------------------------------------------------
-- 8) Financeiro Geral: Custos/Lucro e fluxo diario passam a refletir
--    despesas PAGAS pela data de pagamento (antes: todas as despesas por
--    data_despesa). Backfill do passo 2 garante que os numeros historicos
--    nao mudam. Mesma assinatura das funcoes (migration 0034) -- zero
--    mudanca no frontend, so a fonte do dado por tras.
-- ---------------------------------------------------------------------------
create or replace function public.fn_financeiro_kpis(
  p_unidade_id bigint,
  p_data_inicio date,
  p_data_fim date,
  p_data_inicio_ant date,
  p_data_fim_ant date,
  p_transporte text default 'todos',
  p_categoria text default 'todos',
  p_forma_pagamento text default 'todas'
)
returns jsonb
language plpgsql
stable
as $$
declare
  v_recebido_atual numeric;
  v_recebido_anterior numeric;
  v_custos_atual numeric;
  v_custos_anterior numeric;
  v_pend_atual jsonb;
  v_pend_anterior jsonb;
  v_a_receber_periodo numeric;
  v_vencido_total numeric;
  v_vencido_count bigint;
  v_faturamento_atual numeric;
  v_faturamento_anterior numeric;
  v_lucro_atual numeric;
  v_lucro_anterior numeric;
  v_inadimplencia_pct numeric;
begin
  select coalesce(sum(valor_servico + valor_transporte), 0)
    into v_recebido_atual
  from public.fn_financeiro_eventos_filtrados(p_unidade_id, p_data_inicio, p_data_fim, p_transporte, p_categoria, p_forma_pagamento);

  select coalesce(sum(valor_servico + valor_transporte), 0)
    into v_recebido_anterior
  from public.fn_financeiro_eventos_filtrados(p_unidade_id, p_data_inicio_ant, p_data_fim_ant, p_transporte, p_categoria, p_forma_pagamento);

  -- Custos = despesas PAGAS no periodo, pela data de pagamento (Parte 3 do
  -- modulo de Gestao de Gastos). Despesas ainda nao tem categoria/forma de
  -- pagamento equivalentes aos filtros de receita, entao esses 2 filtros
  -- continuam sem se aplicar aqui.
  select coalesce(sum(d.valor_total), 0)
    into v_custos_atual
  from public.despesas d
  where (p_unidade_id is null or d.unidade_id = p_unidade_id)
    and d.status = 'pago'
    and d.data_pagamento between p_data_inicio and p_data_fim;

  select coalesce(sum(d.valor_total), 0)
    into v_custos_anterior
  from public.despesas d
  where (p_unidade_id is null or d.unidade_id = p_unidade_id)
    and d.status = 'pago'
    and d.data_pagamento between p_data_inicio_ant and p_data_fim_ant;

  v_pend_atual := public.fn_financeiro_contas_pendentes_valor(p_unidade_id, p_data_inicio, p_data_fim, p_transporte, p_categoria, p_forma_pagamento);
  v_pend_anterior := public.fn_financeiro_contas_pendentes_valor(p_unidade_id, p_data_inicio_ant, p_data_fim_ant, p_transporte, p_categoria, p_forma_pagamento);

  v_a_receber_periodo := (v_pend_atual->>'a_receber_periodo')::numeric;
  v_vencido_total := (v_pend_atual->>'vencido_total')::numeric;
  v_vencido_count := (v_pend_atual->>'vencido_count')::bigint;

  v_faturamento_atual := v_recebido_atual + v_a_receber_periodo;
  v_faturamento_anterior := v_recebido_anterior + (v_pend_anterior->>'a_receber_periodo')::numeric;

  v_lucro_atual := v_recebido_atual - v_custos_atual;
  v_lucro_anterior := v_recebido_anterior - v_custos_anterior;

  v_inadimplencia_pct := case
    when (v_recebido_atual + v_vencido_total) > 0
      then round((v_vencido_total / (v_recebido_atual + v_vencido_total)) * 100, 1)
    else 0
  end;

  return jsonb_build_object(
    'faturamento_atual', v_faturamento_atual,
    'faturamento_anterior', v_faturamento_anterior,
    'recebido_atual', v_recebido_atual,
    'recebido_anterior', v_recebido_anterior,
    'a_receber_periodo', v_a_receber_periodo,
    'custos_atual', v_custos_atual,
    'custos_anterior', v_custos_anterior,
    'lucro_atual', v_lucro_atual,
    'lucro_anterior', v_lucro_anterior,
    'inadimplencia_pct', v_inadimplencia_pct,
    'vencido_total', v_vencido_total,
    'vencido_count', v_vencido_count
  );
end;
$$;

create or replace function public.fn_financeiro_fluxo_diario(
  p_unidade_id bigint,
  p_data_inicio date,
  p_data_fim date,
  p_transporte text default 'todos',
  p_categoria text default 'todos',
  p_forma_pagamento text default 'todas'
)
returns table (bucket date, receita numeric, custo numeric, lucro numeric)
language sql
stable
as $$
  with dias as (
    select generate_series(p_data_inicio, p_data_fim, interval '1 day')::date as bucket
  ),
  receitas as (
    select data_evento as bucket, sum(valor_servico + valor_transporte) as receita
    from public.fn_financeiro_eventos_filtrados(p_unidade_id, p_data_inicio, p_data_fim, p_transporte, p_categoria, p_forma_pagamento)
    group by data_evento
  ),
  custos as (
    select d.data_pagamento as bucket, sum(d.valor_total) as custo
    from public.despesas d
    where (p_unidade_id is null or d.unidade_id = p_unidade_id)
      and d.status = 'pago'
      and d.data_pagamento between p_data_inicio and p_data_fim
    group by d.data_pagamento
  )
  select
    dias.bucket,
    coalesce(receitas.receita, 0) as receita,
    coalesce(custos.custo, 0) as custo,
    coalesce(receitas.receita, 0) - coalesce(custos.custo, 0) as lucro
  from dias
  left join receitas on receitas.bucket = dias.bucket
  left join custos on custos.bucket = dias.bucket
  order by dias.bucket;
$$;
