-- Merge de clientes vindos do link publico de auto-cadastro com clientes ja
-- existentes. Aditiva: so adiciona colunas/tabelas/funcoes novas, nenhum drop
-- de dado. Objetivo:
--   1. cadastro_publico_tutor_pets passa a casar telefone tolerando variacoes
--      (com/sem DDD, com/sem 9o digito) e nunca apaga campo bom com vazio.
--   2. Nome parecido mas telefone diferente NUNCA mescla sozinho: vai para a
--      fila clientes_duplicados_pendentes para revisao manual.
--   3. Todo merge grava diff antes/depois em clientes_merge_log (auditoria e
--      possibilidade de reversao).
--   4. mesclar_clientes/rejeitar_duplicado_cliente atendem os botoes da tela
--      de revisao; detectar_duplicados_retroativos so povoa a fila (nunca
--      mescla sozinha) para os duplicados que ja existem hoje.

begin;

create extension if not exists pg_trgm;

alter table public.clientes
  add column if not exists mesclado_no_cliente_id bigint references public.clientes(id) on delete set null;

create index if not exists idx_clientes_mesclado_no_cliente_id
  on public.clientes(mesclado_no_cliente_id)
  where mesclado_no_cliente_id is not null;

create table if not exists public.clientes_duplicados_pendentes (
  id bigint primary key generated by default as identity,
  cliente_id_existente bigint not null references public.clientes(id) on delete cascade,
  cliente_id_novo bigint not null references public.clientes(id) on delete cascade,
  unidade_id bigint not null references public.unidades(id) on delete cascade,
  motivo text not null,
  similaridade numeric(4,3),
  status text not null default 'pendente',
  resolvido_por_user_id uuid references auth.users(id) on delete set null,
  resolvido_em timestamptz,
  created_at timestamptz not null default now(),
  constraint clientes_duplicados_pendentes_status_check check (status in ('pendente', 'mesclado', 'rejeitado')),
  constraint clientes_duplicados_pendentes_diferentes check (cliente_id_existente <> cliente_id_novo)
);

create unique index if not exists uq_clientes_duplicados_pendentes_par_ativo
on public.clientes_duplicados_pendentes(cliente_id_existente, cliente_id_novo)
where status = 'pendente';

create table if not exists public.clientes_merge_log (
  id bigint primary key generated by default as identity,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  unidade_id bigint not null references public.unidades(id) on delete cascade,
  origem text not null default 'cadastro_publico',
  cliente_removido_id bigint references public.clientes(id) on delete set null,
  campos_alterados jsonb not null default '{}'::jsonb,
  executado_por_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_clientes_merge_log_cliente on public.clientes_merge_log(cliente_id);
create index if not exists idx_clientes_duplicados_pendentes_status on public.clientes_duplicados_pendentes(status);
create index if not exists idx_clientes_duplicados_pendentes_unidade on public.clientes_duplicados_pendentes(unidade_id);

-- Gera as variacoes plausiveis de um telefone brasileiro a partir dos digitos
-- puros: com/sem DDD, com/sem 9o digito extra do celular. Comparar por
-- sobreposicao (&&) em vez de igualdade estrita cobre casos como
-- "(18) 99651-5957" = "18996515957" = "996515957".
create or replace function public.telefone_variantes(p_telefone text)
returns text[]
language plpgsql
immutable
as $$
declare
  v_digits text;
  v_sem_ddd text;
  v_variantes text[] := array[]::text[];
begin
  v_digits := regexp_replace(coalesce(p_telefone, ''), '\D', '', 'g');

  if length(v_digits) < 8 then
    return v_variantes;
  end if;

  -- numero completo com DDD (10 ou 11 digitos)
  if length(v_digits) in (10, 11) then
    v_variantes := array_append(v_variantes, v_digits);

    -- alterna com/sem o 9o digito do celular, mantendo o DDD
    if length(v_digits) = 11 then
      v_variantes := array_append(v_variantes, substr(v_digits, 1, 2) || substr(v_digits, 4));
    else
      v_variantes := array_append(v_variantes, substr(v_digits, 1, 2) || '9' || substr(v_digits, 3));
    end if;
  else
    v_variantes := array_append(v_variantes, v_digits);
  end if;

  -- numero sem DDD (8 ou 9 digitos finais), para casar com cadastros antigos
  -- que foram salvos sem o codigo de area
  if length(v_digits) >= 10 then
    v_sem_ddd := substr(v_digits, 3);
  else
    v_sem_ddd := v_digits;
  end if;

  if length(v_sem_ddd) = 9 then
    v_variantes := array_append(v_variantes, v_sem_ddd);
    v_variantes := array_append(v_variantes, substr(v_sem_ddd, 2));
  elsif length(v_sem_ddd) = 8 then
    v_variantes := array_append(v_variantes, v_sem_ddd);
    v_variantes := array_append(v_variantes, '9' || v_sem_ddd);
  else
    v_variantes := array_append(v_variantes, v_sem_ddd);
  end if;

  return (select array_agg(distinct v) from unnest(v_variantes) v where v <> '');
end;
$$;

create or replace function public.registrar_merge_cliente(
  p_cliente_id bigint,
  p_unidade_id bigint,
  p_origem text,
  p_campos_alterados jsonb,
  p_cliente_removido_id bigint default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_campos_alterados = '{}'::jsonb and p_cliente_removido_id is null then
    return;
  end if;

  insert into public.clientes_merge_log (
    cliente_id, unidade_id, origem, cliente_removido_id, campos_alterados, executado_por_user_id
  ) values (
    p_cliente_id, p_unidade_id, p_origem, p_cliente_removido_id, p_campos_alterados, auth.uid()
  );
exception when others then
  null;
end;
$$;

-- Substitui a versao de 0029: mesmo contrato (mesma assinatura, mesmo nome de
-- funcao), so muda o comportamento interno do casamento/merge.
create or replace function public.cadastro_publico_tutor_pets(
  p_unidade_id bigint,
  p_tutor jsonb,
  p_pets jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_unidade_ativa boolean;
  v_cliente_id bigint;
  v_cliente_existente boolean := false;
  v_nome text;
  v_telefone text;
  v_telefone_normalizado text;
  v_cpf text;
  v_cpf_normalizado text;
  v_pet jsonb;
  v_pet_nome text;
  v_pet_id bigint;
  v_pet_resultado jsonb := '[]'::jsonb;
  v_cliente_antes public.clientes;
  v_campos jsonb := '{}'::jsonb;
  v_novo_valor text;
  v_similar record;
begin
  select ativo into v_unidade_ativa from public.unidades where id = p_unidade_id;
  if v_unidade_ativa is null or v_unidade_ativa = false then
    return jsonb_build_object('ok', false, 'erro', 'unidade_invalida');
  end if;

  v_nome := trim(coalesce(p_tutor->>'nome', ''));
  if v_nome = '' then
    return jsonb_build_object('ok', false, 'erro', 'nome_obrigatorio');
  end if;

  if jsonb_array_length(coalesce(p_pets, '[]'::jsonb)) = 0 then
    return jsonb_build_object('ok', false, 'erro', 'pet_obrigatorio');
  end if;

  v_telefone := trim(coalesce(p_tutor->>'telefone', ''));
  v_telefone_normalizado := regexp_replace(v_telefone, '\D', '', 'g');
  v_cpf := trim(coalesce(p_tutor->>'cpf', ''));
  v_cpf_normalizado := regexp_replace(v_cpf, '\D', '', 'g');

  if v_cpf_normalizado <> '' and not public.cpf_valido(v_cpf_normalizado) then
    return jsonb_build_object('ok', false, 'erro', 'cpf_invalido');
  end if;

  -- Localiza cliente existente: telefone (tolerando DDD/9o digito) primeiro,
  -- CPF como fallback.
  if v_telefone_normalizado <> '' then
    select c.id into v_cliente_id
    from public.clientes c
    where c.ativo = true
      and public.telefone_variantes(v_telefone) && public.telefone_variantes(c.telefone)
    order by (c.telefone = v_telefone) desc, c.id
    limit 1;
  end if;

  if v_cliente_id is null and v_cpf_normalizado <> '' then
    select id into v_cliente_id
    from public.clientes
    where ativo = true
      and regexp_replace(coalesce(cpf, ''), '\D', '', 'g') = v_cpf_normalizado
    limit 1;
  end if;

  if v_cliente_id is not null then
    v_cliente_existente := true;

    select * into v_cliente_antes from public.clientes where id = v_cliente_id;

    -- So sobrescreve o que veio preenchido; campo que o link nao mandou
    -- mantem o valor antigo (nunca apaga dado bom com vazio).
    update public.clientes set
      unidade_id = p_unidade_id,
      unidade_preferencial_id = p_unidade_id,
      nome = coalesce(nullif(v_nome, ''), nome),
      telefone = coalesce(nullif(v_telefone, ''), telefone),
      cpf = coalesce(nullif(v_cpf, ''), cpf),
      cep = coalesce(nullif(trim(coalesce(p_tutor->>'cep', '')), ''), cep),
      logradouro = coalesce(nullif(trim(coalesce(p_tutor->>'logradouro', '')), ''), logradouro),
      numero = coalesce(nullif(trim(coalesce(p_tutor->>'numero', '')), ''), numero),
      bairro = coalesce(nullif(trim(coalesce(p_tutor->>'bairro', '')), ''), bairro),
      cidade = coalesce(nullif(trim(coalesce(p_tutor->>'cidade', '')), ''), cidade),
      estado = coalesce(nullif(trim(coalesce(p_tutor->>'estado', '')), ''), estado),
      receber_msgs = true,
      origem_id = 'cadastro_publico',
      updated_at = now()
    where id = v_cliente_id;

    select
      jsonb_strip_nulls(jsonb_build_object(
        'nome', case when v_cliente_antes.nome is distinct from nullif(v_nome, '') and nullif(v_nome, '') is not null
          then jsonb_build_object('antes', v_cliente_antes.nome, 'depois', v_nome) end,
        'telefone', case when v_cliente_antes.telefone is distinct from nullif(v_telefone, '') and nullif(v_telefone, '') is not null
          then jsonb_build_object('antes', v_cliente_antes.telefone, 'depois', v_telefone) end,
        'cpf', case when v_cliente_antes.cpf is distinct from nullif(v_cpf, '') and nullif(v_cpf, '') is not null
          then jsonb_build_object('antes', v_cliente_antes.cpf, 'depois', v_cpf) end,
        'cep', case when v_cliente_antes.cep is distinct from nullif(trim(coalesce(p_tutor->>'cep', '')), '') and nullif(trim(coalesce(p_tutor->>'cep', '')), '') is not null
          then jsonb_build_object('antes', v_cliente_antes.cep, 'depois', p_tutor->>'cep') end,
        'logradouro', case when v_cliente_antes.logradouro is distinct from nullif(trim(coalesce(p_tutor->>'logradouro', '')), '') and nullif(trim(coalesce(p_tutor->>'logradouro', '')), '') is not null
          then jsonb_build_object('antes', v_cliente_antes.logradouro, 'depois', p_tutor->>'logradouro') end
      ))
    into v_campos;

    perform public.registrar_merge_cliente(v_cliente_id, p_unidade_id, 'cadastro_publico', coalesce(v_campos, '{}'::jsonb));
  else
    insert into public.clientes (
      unidade_id, unidade_preferencial_id, nome, telefone, cpf,
      cep, logradouro, numero, bairro, cidade, estado,
      receber_msgs, origem_id
    ) values (
      p_unidade_id, p_unidade_id, v_nome, nullif(v_telefone, ''), nullif(v_cpf, ''),
      nullif(trim(coalesce(p_tutor->>'cep', '')), ''),
      nullif(trim(coalesce(p_tutor->>'logradouro', '')), ''),
      nullif(trim(coalesce(p_tutor->>'numero', '')), ''),
      nullif(trim(coalesce(p_tutor->>'bairro', '')), ''),
      nullif(trim(coalesce(p_tutor->>'cidade', '')), ''),
      nullif(trim(coalesce(p_tutor->>'estado', '')), ''),
      true, 'cadastro_publico'
    )
    returning id into v_cliente_id;

    -- Telefone/CPF nao bateram com ninguem. Se o nome for muito parecido com
    -- um cliente ja existente, nao mescla sozinho: so registra na fila de
    -- revisao manual.
    for v_similar in
      select c.id, similarity(lower(c.nome), lower(v_nome)) as sim
      from public.clientes c
      where c.ativo = true
        and c.id <> v_cliente_id
        and similarity(lower(c.nome), lower(v_nome)) > 0.45
      order by sim desc
      limit 3
    loop
      insert into public.clientes_duplicados_pendentes (
        cliente_id_existente, cliente_id_novo, unidade_id, motivo, similaridade
      ) values (
        v_similar.id, v_cliente_id, p_unidade_id, 'nome_similar', v_similar.sim
      )
      on conflict (cliente_id_existente, cliente_id_novo) where status = 'pendente' do nothing;
    end loop;
  end if;

  -- Upsert de cada pet: casa por cliente_id + nome (case-insensitive).
  for v_pet in select * from jsonb_array_elements(p_pets)
  loop
    v_pet_nome := trim(coalesce(v_pet->>'nome', ''));
    if v_pet_nome = '' then
      continue;
    end if;

    select id into v_pet_id
    from public.pets
    where cliente_id = v_cliente_id
      and lower(trim(nome)) = lower(v_pet_nome)
    limit 1;

    if v_pet_id is not null then
      update public.pets set
        genero = coalesce(nullif(trim(coalesce(v_pet->>'genero', '')), ''), genero),
        especie = coalesce(nullif(trim(coalesce(v_pet->>'especie', '')), ''), especie),
        raca = coalesce(nullif(trim(coalesce(v_pet->>'raca', '')), ''), raca),
        porte = coalesce(nullif(trim(coalesce(v_pet->>'porte', '')), ''), porte),
        restricoes = coalesce(nullif(trim(coalesce(v_pet->>'restricoes', '')), ''), restricoes),
        comportamento = coalesce(nullif(trim(coalesce(v_pet->>'comportamento', '')), ''), comportamento),
        notas_internas = coalesce(nullif(trim(coalesce(v_pet->>'notas_internas', '')), ''), notas_internas),
        origem_id = 'cadastro_publico',
        updated_at = now()
      where id = v_pet_id;
    else
      insert into public.pets (
        unidade_id, cliente_id, nome, genero, especie, raca, porte,
        restricoes, comportamento, notas_internas, origem_id
      ) values (
        p_unidade_id, v_cliente_id, v_pet_nome,
        nullif(trim(coalesce(v_pet->>'genero', '')), ''),
        nullif(trim(coalesce(v_pet->>'especie', '')), ''),
        nullif(trim(coalesce(v_pet->>'raca', '')), ''),
        nullif(trim(coalesce(v_pet->>'porte', '')), ''),
        nullif(trim(coalesce(v_pet->>'restricoes', '')), ''),
        nullif(trim(coalesce(v_pet->>'comportamento', '')), ''),
        'cadastro_publico'
      )
      returning id into v_pet_id;
    end if;

    v_pet_resultado := v_pet_resultado || jsonb_build_object('pet_id', v_pet_id, 'pet_nome', v_pet_nome);
  end loop;

  return jsonb_build_object(
    'ok', true,
    'cliente_id', v_cliente_id,
    'cliente_nome', v_nome,
    'cliente_existente', v_cliente_existente,
    'pets', v_pet_resultado
  );
end;
$$;

-- Mescla manual: reatribui tudo do cliente perdedor para o cliente vencedor,
-- copia so os campos vazios (nunca sobrescreve dado bom), marca o perdedor
-- como inativo (nunca apaga a linha) e resolve a fila.
create or replace function public.mesclar_clientes(p_manter_id bigint, p_remover_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_manter public.clientes;
  v_remover public.clientes;
  v_campos jsonb := '{}'::jsonb;
begin
  if p_manter_id = p_remover_id then
    raise exception 'Nao e possivel mesclar um cliente com ele mesmo.';
  end if;

  select * into v_manter from public.clientes where id = p_manter_id for update;
  select * into v_remover from public.clientes where id = p_remover_id for update;

  if not found or v_manter.id is null then
    raise exception 'Cliente a manter nao encontrado.';
  end if;
  if v_remover.id is null then
    raise exception 'Cliente a remover nao encontrado.';
  end if;

  if not (
    public.is_master()
    or (public.can_access_unidade(v_manter.unidade_id) and public.can_access_unidade(v_remover.unidade_id))
  ) then
    raise exception 'Usuario sem permissao para mesclar estes clientes.';
  end if;

  update public.clientes set
    nome = coalesce(nullif(v_manter.nome, ''), v_remover.nome),
    telefone = coalesce(nullif(v_manter.telefone, ''), v_remover.telefone),
    telefone_adicional = coalesce(nullif(v_manter.telefone_adicional, ''), v_remover.telefone_adicional),
    email = coalesce(v_manter.email, v_remover.email),
    cpf = coalesce(nullif(v_manter.cpf, ''), v_remover.cpf),
    data_nascimento = coalesce(v_manter.data_nascimento, v_remover.data_nascimento),
    genero = coalesce(nullif(v_manter.genero, ''), v_remover.genero),
    notas_internas = coalesce(nullif(v_manter.notas_internas, ''), v_remover.notas_internas),
    restricoes = coalesce(nullif(v_manter.restricoes, ''), v_remover.restricoes),
    logradouro = coalesce(nullif(v_manter.logradouro, ''), v_remover.logradouro),
    cep = coalesce(nullif(v_manter.cep, ''), v_remover.cep),
    numero = coalesce(nullif(v_manter.numero, ''), v_remover.numero),
    bairro = coalesce(nullif(v_manter.bairro, ''), v_remover.bairro),
    complemento = coalesce(nullif(v_manter.complemento, ''), v_remover.complemento),
    cidade = coalesce(nullif(v_manter.cidade, ''), v_remover.cidade),
    estado = coalesce(nullif(v_manter.estado, ''), v_remover.estado),
    foto_url = coalesce(v_manter.foto_url, v_remover.foto_url),
    updated_at = now()
  where id = p_manter_id;

  update public.pets set cliente_id = p_manter_id where cliente_id = p_remover_id;
  update public.pacotes set cliente_id = p_manter_id where cliente_id = p_remover_id;
  update public.agendamentos set cliente_id = p_manter_id where cliente_id = p_remover_id;
  update public.financeiro_movimentos set cliente_id = p_manter_id where cliente_id = p_remover_id;
  update public.whatsapp_mensagens set cliente_id = p_manter_id where cliente_id = p_remover_id;
  update public.notas_fiscais set cliente_id = p_manter_id where cliente_id = p_remover_id;

  update public.clientes set
    ativo = false,
    mesclado_no_cliente_id = p_manter_id,
    updated_at = now()
  where id = p_remover_id;

  v_campos := jsonb_build_object('cliente_removido_id', p_remover_id, 'cliente_removido_nome', v_remover.nome);

  perform public.registrar_merge_cliente(p_manter_id, v_manter.unidade_id, 'mesclagem_manual', v_campos, p_remover_id);

  update public.clientes_duplicados_pendentes set
    status = 'mesclado',
    resolvido_por_user_id = auth.uid(),
    resolvido_em = now()
  where status = 'pendente'
    and (
      (cliente_id_existente = p_manter_id and cliente_id_novo = p_remover_id)
      or (cliente_id_existente = p_remover_id and cliente_id_novo = p_manter_id)
    );
end;
$$;

create or replace function public.rejeitar_duplicado_cliente(p_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_registro public.clientes_duplicados_pendentes;
begin
  select * into v_registro from public.clientes_duplicados_pendentes where id = p_id;

  if not found then
    raise exception 'Registro de duplicado nao encontrado.';
  end if;

  if not (public.is_master() or public.can_access_unidade(v_registro.unidade_id)) then
    raise exception 'Usuario sem permissao para revisar este duplicado.';
  end if;

  update public.clientes_duplicados_pendentes set
    status = 'rejeitado',
    resolvido_por_user_id = auth.uid(),
    resolvido_em = now()
  where id = p_id;
end;
$$;

-- So popula a fila de revisao para os duplicados que ja existem hoje (mesmo
-- telefone em cadastros diferentes). Nunca mescla sozinha.
create or replace function public.detectar_duplicados_retroativos()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_grupo record;
  v_ids bigint[];
  v_principal bigint;
  v_outro bigint;
  v_inseridos integer := 0;
begin
  if not public.is_master() then
    raise exception 'Somente o master pode rodar a deteccao retroativa de duplicados.';
  end if;

  for v_grupo in
    select variante, array_agg(distinct c.id order by c.id) as ids
    from public.clientes c
    cross join lateral unnest(public.telefone_variantes(c.telefone)) as variante
    where c.ativo = true and c.telefone is not null and c.telefone <> ''
    group by variante
    having count(distinct c.id) > 1
  loop
    v_ids := v_grupo.ids;
    v_principal := v_ids[1];

    foreach v_outro in array v_ids[2:array_length(v_ids, 1)]
    loop
      insert into public.clientes_duplicados_pendentes (
        cliente_id_existente, cliente_id_novo, unidade_id, motivo
      )
      select v_principal, v_outro, c.unidade_id, 'retroativo_telefone'
      from public.clientes c
      where c.id = v_principal
      on conflict (cliente_id_existente, cliente_id_novo) where status = 'pendente' do nothing;

      get diagnostics v_inseridos = row_count;
    end loop;
  end loop;

  return (select count(*) from public.clientes_duplicados_pendentes where motivo = 'retroativo_telefone' and status = 'pendente');
end;
$$;

alter table public.clientes_duplicados_pendentes enable row level security;
alter table public.clientes_merge_log enable row level security;

drop policy if exists "clientes_duplicados_pendentes_select" on public.clientes_duplicados_pendentes;
create policy "clientes_duplicados_pendentes_select"
on public.clientes_duplicados_pendentes for select to authenticated
using (public.is_master() or public.can_access_unidade(unidade_id));

drop policy if exists "clientes_merge_log_select" on public.clientes_merge_log;
create policy "clientes_merge_log_select"
on public.clientes_merge_log for select to authenticated
using (public.is_master() or public.can_access_unidade(unidade_id));

-- Status da fila de revisao so muda via mesclar_clientes/rejeitar_duplicado_cliente
-- (security definer): nenhuma escrita direta de authenticated na tabela.
grant select on public.clientes_duplicados_pendentes to authenticated;
revoke insert, update, delete on public.clientes_duplicados_pendentes from authenticated;
grant select on public.clientes_merge_log to authenticated;
revoke insert, update, delete on public.clientes_merge_log from authenticated;

revoke execute on function public.registrar_merge_cliente(bigint, bigint, text, jsonb, bigint) from public;
revoke execute on function public.mesclar_clientes(bigint, bigint) from public, anon;
revoke execute on function public.rejeitar_duplicado_cliente(bigint) from public, anon;
revoke execute on function public.detectar_duplicados_retroativos() from public, anon;
grant execute on function public.mesclar_clientes(bigint, bigint) to authenticated;
grant execute on function public.rejeitar_duplicado_cliente(bigint) to authenticated;
grant execute on function public.detectar_duplicados_retroativos() to authenticated;

commit;
